import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import type { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { backfillMediaDimensions } from "../src/media/dimension-backfill.js";
import { runTestMigrations, setupTestDb, teardownTestDb } from "./db/setup.js";

const PNG_1280x720 = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAABQAAAALQCAYAAADPfd1WAAAACXBIWXMAAAsTAAALEwEA" +
    "mpwYAAAgAElEQVR4nOzdBZck2XUgYP8itddCi2VbLNliS7YshrXYsiRbDLakVUnDzKCZ" +
    "HmaKaWZm5mmYruZpZog9N8clp2Y6p+JlRmZEZX73nHuOd51T+erGl6+dtx78RfaqoVyq" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMAAA0N9WYO/qHoAUg0YYIABBhhggAEGGGCAAQYYYIAB" +
    "BhgY0gCEwETAAAMMMMAAAwwwwAADDDDAAAMMMMDAUGcrAIUQQgghhBBCCCGEEGM/NACF" +
    "EEIIIYQQQgghhOjj0AAUQgghhBBCCCGEEKKPQwNQCCGEEEIIIYQQQog+Dg1AIYQQQggh" +
    "hBBCCCH6ODQAhRBCCCGEEEIIIYTo40huALpe2RXbDDDAAAMMMMAAAwwwwAADDDDAAAMM" +
    "DNWuBhqANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjINQAhMBAwwwAADDDDAAAMMMMAA" +
    "AwwwwAADDGRWAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCzBRgCEwEDDDDAAAMMMMAA" +
    "AwwwwAADDDDAQP8bcAZgDR6CVAMGGGCAAQYYYIABBhhggAEGGGCAgUwDEAITAQMMMMAA" +
    "AwwwwAADDDDAAAMMMMAAA5kVgBCYCBhggAEGGGCAAQYYYIABBhhggAEGGMhsAYbARMAA" +
    "AwwwwAADDDDAAAMMMMAAAwww0P8GnAFYg4cg1YABBhhggAEGGGCAAQYYYIABBhhgINMA" +
    "hMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYFIAQmAgYYYIABBhhggAEGGGCAAQYYYIAB" +
    "BjJbgCEwETDAAAMMMMAAAwwwwAADDDDAAAMM9L8BZwDW4CFINWCAAQYYYIABBhhggAEG" +
    "GGCAAQYYyDQAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkFkBCIGJgAEGGGCAAQYYYIAB" +
    "BhhggAEGGGCAgcwWYAhMBAwwwAADDDDAAAMMMMAAAwwwwAAD/W/AGYA1eAhSDRhggAEG" +
    "GGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMMZFYAQmAiYIAB" +
    "BhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAADDDDAAAMMMMBA/xtwBmAN" +
    "HoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAADDDDAAAMMMMAAAwwwwAAD" +
    "VgBCYCJggAEGGGCAAQYYYIABBhhggAEGGGAgtwUYAhMBAwwwwAADDDDAAAMMMMAAAwww" +
    "wMAAGGgVza/5i9T/QKoBAwwwwAADDDDAAAMMMMAAAwwwwAADQ7WogQZgDR6CVAMGGGCA" +
    "AQYYYIABBhhggAEGGGCAgUwDEAITAQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCYCBhg" +
    "gAEGGGCAAQYYYIABBhhggAEGGMhsAYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8GnAFY" +
    "g4cg1YABBhhggAEGGGCAAQYYYIABBhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDA" +
    "QGYFIAQmAgYYYIABBhhggAEGGGCAAQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAADDDDA" +
    "AAMM9L8BZwDW4CFINWCAAQYYYIABBhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAADDDDA" +
    "AAMMMMAAAwwwkFkBCIGJgAEGGGCAAQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAADDDDA" +
    "AAMMMMAAAwwwwAAD/W/AGYA1eAhSDRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDA" +
    "AAMMMMAAAwwwwAADDDDAAAMMZFYAQmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMFGAIT" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMBA/xtwBmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICB" +
    "TAMQAhMBAwwwwAADDDDAAAMMMMAAAwwwwAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCA" +
    "AQYYyGwBhsBEwAADDDDAAAMMMMAAAwwwwAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIAB" +
    "BhhggAEGGGAg0wCEwETAAAMMMMAAAwwwwAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCA" +
    "AQYYYIABBhhggAEGMluAITARMMAAAwwwwAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIAB" +
    "BhhggAEGGGCAAQYYYIABBhjINAAhMBEwwAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmA" +
    "AQYYYIABBhhggAEGGGCAAQYYYICBzBZgCEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZ" +
    "gDV4CFINGGCAAQYYYIABBhhggAEGGGCAAQY0ACEwETDAAAMMMMAAAwwwwAADDDDAAAMM" +
    "MJBbAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHcFmAITAQMMMAAAwwwwAADDDDAAAMM" +
    "MMAAAwNgoFU0v+YvUv8DqQYMMMAAAwwwwAADDDDAAAMMMMAAAwwM1aIGGoA1eAhSDRhg" +
    "gAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMMZFYAQmAi" +
    "YIABBhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAADDDDAAAMMMMBA/xtw" +
    "BmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAADDDDAAAMMMMAAAwww" +
    "wAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCAAQYYyGwBhsBEwAADDDDAAAMMMMAAAwww" +
    "wAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIABBhhggAEGGGAg0wCEwETAAAMMMMAAAwww" +
    "wAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCAAQYYYIABBhhggAEGMluAITARMMAAAwww" +
    "wAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIABBhhggAEGGGCAAQYYYIABBhjINAAhMBEw" +
    "wAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmAAQYYYIABBhhggAEGGGCAAQYYYICBzBZg" +
    "CEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZgDV4CFINGGCAAQYYYIABBhhggAEGGGCA" +
    "AQYyDUAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxkVgBCYCJggAEGGGCAAQYYYIABBhhg" +
    "gAEGGGAgswUYAhMBAwwwwAADDDDAAAMMMMAAAwwwwED/G3AGYA0eglQDBhhggAEGGGCA" +
    "AQYYYIABBhhggIFMAxACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZFYAQmAgYYIABBhhg" +
    "gAEGGGCAAQYYYIABBhjIbAGGwETAAAMMMMAAAwwwwAADDDDAAAMMMND/BpwBWIOHINWA" +
    "AQYYYIABBhhggAEGGGCAAQYYYCDTAITARMAAAwwwwAADDDDAAAMMMMAAAwwwwEBmBSAE" +
    "JgIGGGCAAQYYYIABBhhggAEGGGCAAQYyW4AhMBEwwAADDDDAAAMMMMAAAwwwwAADDPS/" +
    "AWcA1uAhSDVggAEGGGCAAQYYYIABBhhggAEGGMg0ACEwETDAAAMMMMAAAwwwwAADDDDA" +
    "AAMMMJBZAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMFmAITAQMMMAAAwwwwAADDDDA" +
    "AAMMMMAAA/1vwBmANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjINQAhMBAwwwAADDDDA" +
    "AAMMMMAAAwwwwAADDGRWAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCzBRgCEwEDDDDA" +
    "AAMMMMAAAwwwwAADDDDAQP8bcAZgDR6CVAMGGGCAAQYYYIABBhhggAEGGGCAgUwDEAIT" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCYCBhggAEGGGCAAQYYYIABBhhggAEGGMhs" +
    "AYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8GnAFYg4cg1YABBhhggAEGGGCAAQYYYIAB" +
    "BhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYFIAQmAgYYYIABBhhggAEGGGCA" +
    "AQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAADDDDAAAMM9L8BZwDW4CFINWCAAQYYYIAB" +
    "BhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkFkBCIGJgAEGGGCA" +
    "AQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAADDDDAAAMMMMAAAwwwwAAD/W/AGYA1eAhS" +
    "DRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMMZFYA" +
    "QmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAADDDDAAAMMMMBA" +
    "/xtwBmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAADDDDAAAMMMMAA" +
    "AwwwwAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCAAQYYyGwBhsBEwAADDDDAAAMMMMAA" +
    "AwwwwAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIABBhhggAEGGGAg0wCEwETAAAMMMMAA" +
    "AwwwwAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCAAQYYYIABBhhggAEGMluAITARMMAA" +
    "AwwwwAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIABBhhggAEGGGCAAQYYYIABBhjINAAh" +
    "MBEwwAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmAAQYYYIABBhhggAEGGGCAAQYYYICB" +
    "zBZgCEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZgDV4CFINGGCAAQYYYIABBhhggAEG" +
    "GGCAAQYyDUAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxkVgBCYCJggAEGGGCAAQYYYIAB" +
    "BhhggAEGGGAgswUYAhMBAwwwwAADDDDAAAMMMMAAAwwwwED/G3AGYA0eglQDBhhggAEG" +
    "GGCAAQYYYIABBhhggIFMAxACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZFYAQmAgYYIAB" +
    "BhhggAEGGGCAAQYYYIABBhjIbAGGwETAAAMMMMAAAwwwwAADDDDAAAMMMND/BpwBWIOH" +
    "INWAAQYYYIABBhhggAEGGGCAAQYYYCDTAITARMAAAwwwwAADDDDAAAMMMMAAAwwwwEBm" +
    "BSAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyW4AhMBEwwAADDDDAAAMMMMAAAwwwwAAD" +
    "DPS/AWcA1uAhSDVggAEGGGCAAQYYYIABBhhggAEGGMg0ACEwETDAAAMMMMAAAwwwwAAD" +
    "DDDAAAMMMJBZAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMFmAITAQMMMAAAwwwwAAD" +
    "DDDAAAMMMMAAA/1vwBmANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjINQAhMBAwwwAAD" +
    "DDDAAAMMMMAAAwwwwAADDGRWAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCzBRgCEwED" +
    "DDDAAAMMMMAAAwwwwAADDDDAQP8bcAZgDR6CVAMGGGCAAQYYYIABBhhggAEGGGCAgUwD" +
    "EAITAQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCYCBhggAEGGGCAAQYYYIABBhhggAEG" +
    "GMhsAYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8GnAFYg4cg1YABBhhggAEGGGCAAQYY" +
    "YIABBhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYFIAQmAgYYYIABBhhggAEG" +
    "GGCAAQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAADDDDAAAMM9L8BZwDW4CFINWCAAQYY" +
    "YIABBhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkFkBCIGJgAEG" +
    "GGCAAQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAADDDDAAAMMMMAAAwwwwAAD/W/AGYA1" +
    "eAhSDRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMM" +
    "ZFYAQmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAADDDDAAAMM" +
    "MMBA/xtwBmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAADDDDAAAMM" +
    "MMAAAwwwwAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCAAQYYyGwBhsBEwAADDDDAAAMM" +
    "MMAAAwwwwAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIABBhhggAEGGGAg0wCEwETAAAMM" +
    "MMAAAwwwwAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCAAQYYYIABBhhggAEGMluAITAR" +
    "MMAAAwwwwAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIABBhhggAEGGGCAAQYYYIABBhjI" +
    "NAAhMBEwwAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmAAQYYYIABBhhggAEGGGCAAQYY" +
    "YICBzBZgCEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZgDV4CFINGGCAAQYYYIABBhhg" +
    "gAEGGGCAAQYyDUAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxkVgBCYCJggAEGGGCAAQYY" +
    "YIABBhhggAEGGGAgswUYAhMBAwwwwAADDDDAAAMMMMAAAwwwwED/G3AGYA0eglQDBhhg" +
    "gAEGGGCAAQYYYIABBhhggIFMAxACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZFYAQmAgY" +
    "YIABBhhggAEGGGCAAQYYYIABBhjIbAGGwETAAAMMMMAAAwwwwAADDDDAAAMMMND/BpwB" +
    "WIOHINWAAQYYYIABBhhggAEGGGCAAQYYYCDTAITARMAAAwwwwAADDDDAAAMMMMAAAwww" +
    "wEBmBSAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyW4AhMBEwwAADDDDAAAMMMMAAAwww" +
    "wAADDPS/AWcA1uAhSDVggAEGGGCAAQYYYIABBhhggAEGGMg0ACEwETDAAAMMMMAAAwww" +
    "wAADDDDAAAMMMJBZAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMFmAITAQMMMAAAwww" +
    "wAADDDDAAAMMMMAAA/1vwBmANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjINQAhMBAww" +
    "wAADDDDAAAMMMMAAAwwwwAADDGRWAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCzBRgC" +
    "EwEDDDDAAAMMMMAAAwwwwAADDDDAQP8bcAZgDR6CVAMGGGCAAQYYYIABBhhggAEGGGCA" +
    "gUwDEAITAQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCYCBhggAEGGGCAAQYYYIABBhhg" +
    "gAEGGMhsAYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8GnAFYg4cg1YABBhhggAEGGGCA" +
    "AQYYYIABBhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYFIAQmAgYYYIABBhhg" +
    "gAEGGGCAAQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAADDDDAAAMM9L8BZwDW4CFINWCA" +
    "AQYYYIABBhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkFkBCIGJ" +
    "gAEGGGCAAQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAADDDDAAAMMMMAAAwwwwAAD/W/A" +
    "GYA1eAhSDRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAADDDDA" +
    "AAMMZFYAQmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAADDDDA" +
    "AAMMMMBA/xtwBmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAADDDDA" +
    "AAMMMMAAAwwwwAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCAAQYYyGwBhsBEwAADDDDA" +
    "AAMMMMAAAwwwwAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIABBhhggAEGGGAg0wCEwETA" +
    "AAMMMMAAAwwwwAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCAAQYYYIABBhhggAEGMluA" +
    "ITARMMAAAwwwwAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIABBhhggAEGGGCAAQYYYIAB" +
    "BhjINAAhMBEwwAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmAAQYYYIABBhhggAEGGGCA" +
    "AQYYYICBzBZgCEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZgDV4CFINGGCAAQYYYIAB" +
    "BhhggAEGGGCAAQYyDUAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxkVgBCYCJggAEGGGCA" +
    "AQYYYIABBhhggAEGGGAgswUYAhMBAwwwwAADDDDAAAMMMMAAAwwwwED/G3AGYA0eglQD" +
    "BhhggAEGGGCAAQYYYIABBhhggIFMAxACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZFYAQ" +
    "mAgYYIABBhhggAEGGGCAAQYYYIABBhjIbAGGwETAAAMMMMAAAwwwwAADDDDAAAMMMND/" +
    "BpwBWIOHINWAAQYYYIABBhhggAEGGGCAAQYYYCDTAITARMAAAwwwwAADDDDAAAMMMMAA" +
    "AwwwwEBmBSAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyW4AhMBEwwAADDDDAAAMMMMAA" +
    "AwwwwAADDPS/AWcA1uAhSDVggAEGGGCAAQYYYIABBhhggAEGGMg0ACEwETDAAAMMMMAA" +
    "AwwwwAADDDDAAAMMMJBZAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMFmAITAQMMMAA" +
    "AwwwwAADDDDAAAMMMMAAA/1vwBmANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjINQAhM" +
    "BAwwwAADDDDAAAMMMMAAAwwwwAADDGRWAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCz" +
    "BRgCEwEDDDDAAAMMMMAAAwwwwAADDDDAQP8bcAZgDR6CVAMGGGCAAQYYYIABBhhggAEG" +
    "GGCAgUwDEAITAQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCYCBhggAEGGGCAAQYYYIAB" +
    "BhhggAEGGMhsAYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8GnAFYg4cg1YABBhhggAEG" +
    "GGCAAQYYYIABBhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYFIAQmAgYYYIAB" +
    "BhhggAEGGGCAAQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAADDDDAAAMM9L8BZwDW4CFI" +
    "NWCAAQYYYIABBhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkFkB" +
    "CIGJgAEGGGCAAQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAADDDDAAAMMMMAAAwwwwAAD" +
    "/W/AGYA1eAhSDRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwEDDDAAAMMMMAAAwwwwAAD" +
    "DDDAAAMMZFYAQmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMFGAITAQMMMMAAAwwwwAAD" +
    "DDDAAAMMMMBA/xtwBmANHoJUAwYYYIABBhhggAEGGGCAAQYYYICBTAMQAhMBAwwwwAAD" +
    "DDDAAAMMMMAAAwwwwAADmRWAEJgIGGCAAQYYYIABBhhggAEGGGCAAQYYyGwBhsBEwAAD" +
    "DDDAAAMMMMAAAwwwwAADDDDQ/wacAViDhyDVgAEGGGCAAQYYYIABBhhggAEGGGAg0wCE" +
    "wETAAAMMMMAAAwwwwAADDDDAAAMMMMBAZgUgBCYCBhhggAEGGGCAAQYYYIABBhhggAEG" +
    "MluAITARMMAAAwwwwAADDDDAAAMMMMAAAwz0vwFnANbgIUg1YIABBhhggAEGGGCAAQYY" +
    "YIABBhjINAAhMBEwwAADDDDAAAMMMMAAAwwwwAADDDCQWQEIgYmAAQYYYIABBhhggAEG" +
    "GGCAAQYYYICBzBZgCEwEDDDAAAMMMMAAAwwwwAADDDDAAAP9b8AZgDV4CFINGGCAAQYY" +
    "YIABBhhggAEGGGCAAQYyDUAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxkVgBCYCJggAEG" +
    "GGCAAQYYYIABBhhggAEGGGAgswUYAhMBAwwwwAADDDDAAAMMMMAAAwwwwED/G3AGYA0e" +
    "glQDBhhggAEGGGCAAQYYYIABBhhggIFMAxACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZ" +
    "FYAQmAgYYIABBhhggAEGGGCAAQYYYIABBhjIbAGGwETAAAMMMMAAAwwwwAADDDDAAAMM" +
    "MND/BpwBWIOHINWAAQYYYIABBhhggAEGGGCAAQYYYCDTAITARMAAAwwwwAADDDDAAAMM" +
    "MMAAAwwwwEBmBSAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyW4AhMBEwwAADDDDAAAMM" +
    "MMAAAwwwwAADDPS/AWcA1uAhSDVggAEGGGCAAQYYYIABBhhggAEGGMg0ACEwETDAAAMM" +
    "MMAAAwwwwAADDDDAAAMMMJBZAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMFmAITAQM" +
    "MMAAAwwwwAADDDDAAAMMMMAAA/1vwBmANXgIUg0YYIABBhhggAEGGGCAAQYYYIABBjIN" +
    "QAhMBAwwwAADDDDAAAMMMMAAAwwwwAADDGRWAEJgImCAAQYYYIABBhhggFF1ehYAACAA" +
    "SURBVAEGGGCAAQYYYCCzBRgCEwEDDDDAAAMMMMAAAwwwwAADDDDAQP8bcAZgDR6CVAMG" +
    "GGCAAQYYYIABBhhggAEGGGCAgUwDEAITAQMMMMAAAwwwwAADDDDAAAMMMMAAA5kVgBCY" +
    "CBhggAEGGGCAAQYYYIABBhhggAEGGMhsAYbARMAAAwwwwAADDDDAAAMMMMAAAwww0P8G" +
    "nAFYg4cg1YABBhhggAEGGGCAAQYYYIABBhhgINMAhMBEwAADDDDAAAMMMMAAAwwwwAAD" +
    "DDDAQGYFIAQmAgYYYIABBhhggAEGGGCAAQYYYIABBjJbgCEwETDAAAMMMMAAAwwwwAAD" +
    "DDDAAAMM9L8BZwDW4CFINWCAAQYYYIABBhhggAEGGGCAAQYYyDQAITARMMAAAwwwwAAD" +
    "DDDAAAMMMMAAAwwwkFkBCIGJgAEGGGCAAQYYYIABBhhggAEGGGCAgcwWYAhMBAwwwAAD" +
    "DDDAAAMMMMAAAwwwwAAD/W/AGYA1eAhSDRhggAEGGGCAAQYYYIABBhhggAEGMg1ACEwE" +
    "DDDAAAMMMMAAAwwwwAADDDDAAAMMZFYAQmAiYIABBhgo38CE116aT3/39fmcT96RL/jS" +
    "vfnCr9z3p5z7qTvzWR+5NZ/81qvUPuo1biif+jfX5LM/dls+7zN3/1mt5n9ufD7nH+/I" +
    "p/3dtfmz/+cP6mW+YoCBUgzEfDL1b6/NZ3/89nz+58f/2bwz71/uavz/x7z07F/+njnm" +
    "GGCAAQYG0kCraH7NX6T+B1INGGCAAQbGqoEJr7mk8WVx7e+n5DseXpEfXPp8fvrgibxo" +
    "nDt1Nj+2eX++K1ubr798er7gC/fkz/7VH/q6Xgu/fF++6brZ+e5J6/Pj2w/mF86eL1as" +
    "C3l+cveRfN/sLfmW2+bnS//t0Xzym6+s/HfqVk5561X50n9/7MVaTViXH9mwNz8xfDg/" +
    "c/hkfuH8hfz86XMNayd2HMwPLt+ZP//IinzdJVMbDecJr76k8vFLNaiDgWjgxR9cVv0i" +
    "y7fdsyTfP3drYx6Jz1Chaefs+cbnbu/0TfmmG+bkS771cD7pry+v/PfqyRz0tqvzZd97" +
    "LN90/Ytz0NGN+/58Djp19s/moPg3cN0fpuYLvmgOqvrZSTVggIGshBq0iubXaADCZsJh" +
    "gIEBNTDjAzflq371bOFc+dNnKh9zO18mYwXfxqtn5i8s2dFowpQdZ4+dzndP3tD44hUN" +
    "s6p/5zJWQ8bvsnfapvzcyTOl1iq+hB5ctjNf89tJfbGiMpp+6y+d1rBVtEHR0tCEdfmy" +
    "7z9u5eQYyXW/n9JoTvVjLvvB4z3/tyjmhGjaxWeh7Iim4IGF21+cd/rsjxDR9Ft/2bTG" +
    "H7M6nYN2PbuuMfdbvV39c5VqwAADWRs1aBXNr9EAhMsEwwADA2Ygtm4OP70m+cvCueOn" +
    "Kx970abf/M+Oz7eNX5yf2ncs72WcOXiisdptytuvrrwOqRlfjDdeOys/c+hkT2p1/sy5" +
    "xiq4+PJf9e+emtPfe0O+7d4lpTdII04OH240lya+/rLKf0/ZugY7Hlqe92vE6uZuP/uZ" +
    "/3BzvvGaWfnRzft7+rvFKrjhJ1fnsz5865j2PeP9N+bb71/aWJVedpzYeShfOzTZHFSD" +
    "5yzVgAEGsoQatIrm12gAQmViYYCBATEQW19jhUVszWwn6t4AjHPnYqXfiecP5VVHNIai" +
    "ETgWtp5Fw3Tt7ybnZ4+eqqRW0Yjeft/SfNKbrqi8FqNlbNUNY9FE6HZEI3Dx1x+s/HeW" +
    "F6+BBmC6jZgPV/0yyw+tHM6rjph3YsXb9PfcMKaMN+aga2Z1ZTX7xRqBi772QOW/s1QD" +
    "BhhgYKhQDVpF82s0AH2gfKAYYKDPDSz86v2N7U+dRl0bgHERRZxP18n2p27FyV1H8sXf" +
    "fKjyGrXKmR+8KT+8Zndehzi9/1itG16xYujopn09r0us1p34hvo3kgctNQDTVqvFiuz4" +
    "N6Ruce7EmcY5eGPh8pDZH72tcQZtr2Pnk6utBqzB85dqwAAD2Sg1aBXNr9EABMlkwgAD" +
    "fWggvszEpQuHV+0q7UtA3RqAsWU1DjIfCxFffut2WciSbz/clfO2OooLeePg/rp9GV/0" +
    "fx+obIVkxJF1e/Jp77yu8jrI/62BBmAxDzsfW1nLP868NA7M39Y4T6+uxuOPI1XO14dX" +
    "726ssq+6DlINGGCAgaGWNWgVza/RAPQh8iFigIE+MhBNphU/fqorqwTq1gCMc9jGUsRF" +
    "EZPfUo8D6Ff9/Jlafyl//tGVtWkCxufpwrmCNx93MeI8y5kfuqXyesj+bwCWeeHTqb1H" +
    "87ESsWI7zsitm/GVP6vHfH1yz9F85t/fXHk9pBowwAADQxetQatofo0GoA+QDxADDPSB" +
    "gbi5dc2vJzbO7OlWaAB2HkfW7638gpBVv8jaPgeyl7HziVV5Nq7az1Vs365D86+5QWEl" +
    "YD2yXxuAcanEpDdeMZANwIi4BGnOp+6s3NdILvnOI7Vo/o1E/N8YU//WSsCqXUg1YICB" +
    "7CI1aBXNr9EAhMcEwgADY9hAHKoeNzbG+WndDg3AciLOkSvzC3ZKLvjivfmFs+U1tOKL" +
    "6emDJ/ITOw42VqjFzb5lRly4UeXZkt24YbPTiFtTx8KFKf2e/doAjBtyy6zTWGsARsR2" +
    "/zqsBJz/ufE9uXAoNY5s2FvZv2FSDRhggIGhljVoFc2v0QD0IfIhYoCBMWhgyluvapyV" +
    "dvZI784l6/cGYJyvdHTjvsZZUHtnbG7cEBn/c5y/FiuvylwJtm/2lp5vcY2Vh6dfON5R" +
    "s++FRTvyTdfPzhd++b6W25knvv6yfM4n78jXDk1uXM7S0cH/F/LGe/XaVjTY4pl3Uqu4" +
    "XGXbPUvy9ZdOy1f96tl89X9PyDdcNSPfla1tbKXrJMJm1Z+/Qc9+bQCW/XkrswEYN98e" +
    "e+5AYx7aP+e5xudg36wt+aFVuxp/hCizWXZi+HClq7Vjfu1knmjMQatfPgfFH1Wibp0+" +
    "l+Gn1lT+GZRqwAADDAz9WQ1aRfNrNAB9cHxwGGBgDBmI7X9b/7iocXNhr6OfGoBnDp/M" +
    "90ze0Fg9Gaviihz+Htus5336rnzjNbNKuQ02Gri9rFd86Wv3i2Q0O6a/78a2V6nGLZux" +
    "UrCdiC/20VTsZa2Gn1nbdhM5GqTT3n39K/78aP4u+MI9+d5pm/J2Y8VPnq78MzjI2Y8N" +
    "wGh6lf2HiXYbTdHsiz/AbL5xbmMr/rR3XTfq2OJ/P+tDt+RrfjspP7BgW8dHHeyft7Wy" +
    "Ywh2T1jX/hx03exGvUarVfzbF3/sajeW//DJyj+HUg0YYICBoT/VoFU010gD0IfGh4YB" +
    "BsaAgRkfuCnf8fCK0rdYDlID8OTw4XzLrfMbjZdn/0/nN/LGz4mLPdqNWFE45xO396RW" +
    "8z8/vq0xnnj+UKPpWcYYosnabsOrl1uBl33vsbbGGL9bO2djxYqrdlb6xBd95wFWN//E" +
    "hSwLv3Jf7TO25heNaF6XXaeUBmCsaH/+kRWNc+/KaPrP/OBN+c4nV3d0ht7q/5rQc1vL" +
    "/+OJtsYaf9Sa+jfXpM9BX72/rUZtbJVu5/2kGjDAAANDXalBq2h+jQagD6APIAMMjAED" +
    "h1ftysuOaECdO3mmrxuAcYZbfKFsNP26tOU2btRtd5trbF3rxQqTWMnSzjlPZX+5i2ew" +
    "7d4lba3Y7MWZU7HKs52LdLbcMq8jX9EcPbhsZ1u3Jffq8ybHXg3mfurO4pgu5I05tewx" +
    "jNZYiubcvplbGo33+Px16yy9di/IikZ7HLnRq2c28bWXNv5YlRqxUrKTf0tiu/OhlcPJ" +
    "7xsrYat2LtWAAQYYGGrUoFU010cD0AfGB4YBBgasARirCHc8uDyf8f4bk1awjaUGYHzp" +
    "jPPWevXFbfbHb297q9uSbz3c1bHN+vCtyWOK36VbNz1Go2z35A3JY4ptfd1+jnFWVmo8" +
    "d+fCUt47tkofXPp80ntH8yTs9cK4HHs12PHAssKWYstsN8bQal6MYyzijwGxSq8XtYh/" +
    "C9ppso80+Hv1zDZcMSN9fLfOL+W9448sh1YMp89BH63+whSpBgwwwMBQy7m6uTYagD4s" +
    "PiwMMDAgDcBY7bf17sV/tm2w3xqAcXFDbNma8OpLKtkS2M45d7Hqopvjii+vqbHo/z7Q" +
    "9QPuU7YmNuq0ort1ii+/qZfqxPlZZa4sjVU4qZePxOqpXluX9a/BxDdc3li9VjRW/Oip" +
    "njQAY0ybb56bT+7hqrrmJntcjJEa0azsxc3bk998ZdIzi9gzdWOpq8hj1XfqkQRx/EHV" +
    "3qUaMMAAA0Mt5+nm2mgA+rD4sDDAQJ83AOMLRTSBLnajYb80AKOZtObXE/MJr+l94++l" +
    "Zym1c97UrI/c2rUxHd/2QtJYDizc3pNaxY2UqdHNM+/i1uKUOHPwRFfOv4ozF5MMXcgb" +
    "Fx9U6V7WrwZxNEHKvxETX3dZVxuAcRxD49+hChp/zRmXY8RnNzVW/+rZro9t3SVTk8YU" +
    "f3Ca8o7y56D5nx2fNAfFa3u1klOqAQMMMDDUsgatovk1GoA+RD5EDDDQpw3A+JITN9bG" +
    "qoJWP3esNwDP/8+XyljZUfV42tl2V/YWrpdmbONNjcVff7AndYrzvs4cOpk0tuX/+URX" +
    "xhKr+FIbpd28HGDrXYuSxrL9/qWVu5f1qsHB5TtrcY5brCbbla3Np49yM3Yvc8WPn8pT" +
    "I7bnd3NMMQfFpUspseoXWdfGs+2etLNat41fXPlzlWrAAAODbqBVNL9GA7AGD0qqAQMM" +
    "lNkAjNVwsZIgtoCN9nPHcgMwmn7dOLS+04yVlrHaJSWOrN/blbEs/fe0G21j+2kvLiUZ" +
    "ybjZOiXiS2k3xrH4Gw8ljePEjoP5s3/V+U3SZTUoerVFUY6NGsSK4pSY95m7uzaWWp5R" +
    "OW4oP7JuT1KNYpVbNy8iWvLth5PGE3+wKOM2+1a58mfFV5COrCKt0x/ipBowwMAgGmgV" +
    "za/RAKzBg5JqwAADZTQATwwfztf8ZmLSTYpjuQFY54xLVlK/XHbjTKzUA+WHn1zd0zqt" +
    "+MnTSePbP+e5roxj17PrksaxqovbAWPF7un9aecjNsb082cqdy/rUYOUFaTHnjtQ+Xir" +
    "yNS5J2LxNx/q2nh2T1qfNJZo0HVrLPFv0ekXjifXJ2pa9XOVasAAA4NsoFU0v0YDsAYP" +
    "SqoBAwx00gA8tvWFfOVPn2lrRZIGYHfsLfjCPXlqLPrXBypfYdeLc66ac/r7bkxeeVf2" +
    "GOLss1hBVzTOHj1VaHVtr5rHI7FvtstAemm3rpm6tX795dMrH3MVGavV4giJlNh0w5yu" +
    "jCXmk5RV42cOn+zamY2Rzz+S9u9G86VIVT9XqQYMMDDIBlpF82s0AGvwoKQaMMBAOw3A" +
    "2Da67AePd3QLqQZgd+zF1qzU2xzX/HZS6ePYM3lD0hjm/ctdPZ+P4nbqohE1Lfv9l373" +
    "0aQabb+ve+ftzf/c+MalHu3EhbPnK7lZVdarBnFOZmEz5y80zgmtesxV5f65W5M+Y3GW" +
    "YTfGsez7j9fmvL3GH6/anIPOnznnKIIauJZqwMDgGmgVza/RAKzBg5JqwAADKQ3AQyuH" +
    "8yXferiUs9o0ALtn78CCbXlKxLa9sscQW2ZTYubf39zz+ejk7iNJDYuy33/46TVJNVrw" +
    "pXu7UocJr74kP7p5f95JrPypLXiDninzzqCv2Np849ykz1f8O1yHIwjmf358V8Yx4TWX" +
    "NLaEdxIrfvhk5c9VqgEDDAyqgVbR/BoNwBo8KKkGDDAwmoH44nFg4fZ84VfvL9WLBuBQ" +
    "bbZR7ezC+XthJiWmvO3qns9HsZK1cFzIO1rx+rIcN9S4NKdoxNbKbh28v/HqmXmn0Q1D" +
    "cuzUYMYHbkpavRWXBFU95iozbtGt+giCmINSzts7ffBEuXNgU266bnbeaTz/6MrKn6tU" +
    "AwYYGFQDraL5NRqANXhQUg0YYKDIF7tuONEA7J69LbfNz1Ni9+QNpY8hfmZKxAqQXs9H" +
    "B5c+n3T+XpnvHSse67AFMD7fqeeRtbzFuYTzyOKZRLOjSB5evTuf/JYre+7mZeN+/WWN" +
    "+azouOMW1dkfva3ycZeZW26ZV9jKmYMnKvm81ymXfOeRpM/X6QPHSx/DrA/fWouLmmb+" +
    "w835+dPn8k7jxPOHKn+uUg0YYGBQDbSK5tdoANbgQUk1YICBqgxoAHavtnG4fkrsm7ml" +
    "8ktAKlkBuGFvZStw4jbflIhbtkuvwbih/MD8tO3irxQz3n9jx2Na8MV7G9uti0acNVnG" +
    "kQS9tB4rLqscb9kZl0ClrGbdenf3zpEbKzn/s+OTzHTjDNI1v55Y/UVN49JXi79STH/3" +
    "9ZU/W6kGDDAwiAZaRfNrNABr8KCkGjDAQFUGNAC7V9toFqVEnANV9hi23Dq//mcA7jla" +
    "eHyHSj6DK1bTpMTsj5W/YmzFj5/Ky4y4EbyMcW28dlb1zdEuXaIQlz90axtlVbk0cTXb" +
    "nE/cXvmYq87ZH789qWYxV5U9hlhVnBKzPnRL6WNY+bNn8jJjxY+eqvzZSjVggIFBNNAq" +
    "ml+jAViDByXVgAEGqjKgAVifFYA7Hlxe+hhW/OTppDHM+8zdvTU4big/l7D1dedj5Z4v" +
    "dXTTvsLvfe746dKbRnFrb5zpVWaUtbIrftf984rfkhpbmKOh0lM/rxrKp7/3hsbW8KIR" +
    "q+SmvOOano+z2xkXehSNI+v2VD7eOmTj1u2EiEt6yh5DyqUbjSMQSl5pG6u+Yzt4mfHc" +
    "nQsrf7ZSDRhgYBANtIrm12gA1uBBSTVggIGqDGgA1uM8rohNN8wpfQzT33dj0hhiO1ov" +
    "/cW5Uymx6uflrG6LjPPPLpw7X/i9D60YLv33jwPzi8SFs8XHGbfAljW+qX9zTdK20mNb" +
    "DjTO4uuVn7iQ5eDynYXHF9uau3WLc5U57V3XJW3ZXvv/JlU+5jrkkm89nKdEmZ+tyImv" +
    "uyzpucXZnGXXIC4OKnsOitvnq362Ug0YYGAQDbSK5tdoANbgQUk1YICBqgxoAHavtnEu" +
    "WkrENsZujCMuhqj6kotWGedZpUSZl+HEFsiU2PFQuSs0F3zhnkI3tu6esC7popS4qbjs" +
    "caY0KeL261752Xzz3DwlYltzL333KlO2a58/cy6f8tarKh9zHXLdJVOT/GwbX+65iXM/" +
    "dWfS+2+/f2klc9DwM2sbfwApGnGrcdXPVqoBAwwMooFW0fwaDcAaPCipBgwwUJUBDcDu" +
    "1TZuGU2JuA2yG+PY8cCywmOI1V69PBtt+Ok1hccW9azy7L21v59S6urDIlv/zh451ViF" +
    "V3SVzkhM/dtrS63VputnJ73/8v98out2Fn75vqTGZFy00m/n/kXG73Ri+HDhOuyeuL7y" +
    "Mdcli67AHYm4NKjKs/fW/La8lZsTX3tpoX+j4g8KsWU+moApMeXtvb9QSqoBAwwMuoFW" +
    "0fwaDcAaPCipBgwwUJUBDcDu1DWaNkVWVjR/yepWc2LWR25NGsuirz3QE3uT3nRFfu7k" +
    "mUq+/EbGluuUWPLth3veUFv1y6ytscbKnjJrFTZj+2PKballrta82Lllp/YeTWpsx2ey" +
    "F657nYv+9YEkG4u//mDlY65LHt9+MKl2MZdWeUzE4m88VNp7b75pbtKlQqljjRuWq36+" +
    "Ug0YYGDQDLSK5tdoANbgQUk1YICBqgxoAHanrvGlKSViJVw3n3Pcelo0wkQv7G26bnbS" +
    "4feT/vryUt9/5+Orkp5RWRdcxLmH50+fG/X9Dizc/qcD/+Psw5SI1Y1lP69ooJ3eX/w8" +
    "wMOrduUTXn1J+XbGpV14EasEY7VgL0xXkbGir2hE0zTOTax6zHXImR+8KU+Jk8OHSx/D" +
    "8FPFV0CXuUo8fk5sBR8t4hKgkTko9biGXqwClmrAAAMMDP1ZDVpF82s0AH1wfHAYYGCA" +
    "DWgAdqeuKQ2KiBU/Kr9h05xx8UGdxhOrw86dOFPpBSnRYEuJUhqQ44byFxbtKHSjbjQo" +
    "Rv67WJWZEhuvntmV57bwK2nbbrd24TbQtUOTk2oRqy27abnKjK2ZKZczxCquqsdcl9xw" +
    "5YxKz99L/fc3oowLdmI1b5EzReN29uZVvIu/+VDSWDdcMaPyZyzVgAEGBs1Aq2h+jQZg" +
    "DR6UVAMGGKjKgAZg+TWd9u7rk5oksV2y7NVtF8uUM5xiTLM/dltXxhG/65F1ewqP5cTz" +
    "hxq3ZZY9jhM7im//i2ZlL8/8iuZE838355N35FVeWNKcSduRL5S75TQubimyenIkYtty" +
    "P577N5LrL5uW5CJWn1Y95tqcm/j8oaTazfvM3aWPI1YVpqyCLuM94xzDIhG2mv+7uf/8" +
    "x8obplINGGCAgaFXrEGraH6NBqAPkg8SAwwMsAENwPJruuXW+WlflB5Y1pNnPfktVyZ9" +
    "4Yxz08ra9to8hhRzF86d78oX71iJl9JIOrHzUMfvGYfix1mPo8WR9XvzZ//qz7dpTnvX" +
    "dXlK7J/zXNccNc4DTFg9GTeClnEpycQ3XJ4f21r8Yp3Yrtyv5/6NGE6px8FlO6sfc01y" +
    "ybcezlPi6MZ9XfkcxfzWy0uQ4vMQFwuNFofX7nnZVvHp770hqWaxCr7q5yzVgAEGBs1A" +
    "q2h+jQZgDR6UVAMGGKjKgAZgufWMRkfKxRaxQqrsJtsrZbxXkS+AI3Hu+Ol89X9NKGUV" +
    "1YIv3pu26uZCnq/6xYuXYJSdk954RfFx5Hl+aNWujt+zyE2+sXJ07j/98aK3BqfE4TW7" +
    "u+789IHjPV2Jl3Jja+Pcv6/e37PPVRUZF72kxMiFMoOe4fDIhr1JtVvz64mlj2PyW69K" +
    "GkMZDdwiq8CjKRkrjl/638b245Q4tHK48mct1YABBgbNQKtofo0GYA0elFQDBhioyoAG" +
    "YLn13PHAsjwl9kzZ2PNnPu/TdzW2+KZErD6JRuDE116a9n7jhhpbQIuce9ftW3+bc/p7" +
    "0laz7Ju5paP3i2ZUkdj6x0Utf0bKmYnRaO22o/idUra6d3IuYVwokBLdODOyblmkoTwS" +
    "8UeJXhwzMBYyLshJiZO7j+QTUue9Ahnn66XE3mmbenJb9HO3L2j5M1JWTZexYlGqAQMM" +
    "MDCUVINW0fwaDUAfLB8sBhgYYAMagOU21lIaIvHa2R/tzjl7o+X8z4/PTx88kadGNBJi" +
    "NVdcrLD0O4/k8z83Pp/1kVvz6e++vnG+WGzXXfyNh/J1l0zN90zd2NZ7xAqUtb+b3NXf" +
    "P86SS4ndE9a1/V7RNI0vw6PFieHDjW2urX5Oyg28scqzF4423zg36bnO/+z45PeY8f4b" +
    "kxrWsT25n8/9i5z85isblzQUjZ1PrKp8zHXIOIIg5XPUzZWTcz91Z9I4YvVeu+8VZ6gW" +
    "WX0d56K+0nmrZxLm85j7q37eUg0YYGDQDLSK5tdoANbgQUk1YICBqgxoAJZTxzizLXVb" +
    "2c7Hq/1SPu3vrm008+oU0QTrypl/Hd6KHKut2n2vzTcVa5LFTb+v9HOObz+Y1FzuRRMs" +
    "zglLWd15cteRRhMm5XMVWwmLRmxLLuO8wbpnrI5Nidh+X/WY65DPP7IiqW7Hthx42Vl4" +
    "ZWXRVcEjEVvgu30u7Wjb5mN+Tmn4xwrwqp+5VAMGGBgkA62i+TUagDV4UFINGGCgKgMa" +
    "gOXUceM1s/KUiMsg4lKIqj/70SSK2x7jhskqIxpW8eU8Vjb14vde+m+PJo1vx8Mr2nqf" +
    "WB15/szo2+aGn1oz6s9KuTk5IqXR1mkjOS76KBp7Jm8o3BhIuVBnEM79+5OF9cX/2BAr" +
    "v/p9RWSRXPiV+xrnihYHlTfOWezWeJZ977GeXBYVt7kXuWykyB+kjm7alzRm286rdy/V" +
    "gIHBMtAqml+jAViDByXVgAEGqjKgAdh5DWPFWsptjhGrfv5MrT730XiLc9NSzwbsNKJp" +
    "E6vrZn7wpp7+vst/+GTSOLfdsyT5PaLpcnDp84W2yk152+jN4CI/qzmiMderesb5Yinb" +
    "39f8ZmLpZwzGSsuqP0e9yLgkJiU2Xjur8jFXnVPeelV+au/RpLrFHyS6OaYVP3k6aTxb" +
    "72p9PugrzUGHVgwXWjkbl5KM9vOK/KzmmPKOPr6FW6oBAwy8qn41aBXNr9EArMGDkmrA" +
    "AANVGdAA7Pw22RM7E262/Z8bUeu6NWrSm67IV/70mXzvjM2FVq61G4dX7crXXz49n/7e" +
    "Gyr5PVf+NO3L93N3Lkx+j9W/erbQz45LCYr8vDjbLiXiopNe1nTzzcXPAzx/6uwr3n4d" +
    "q2NP7St+VltsQ+7WVs265Y6HlheuSzRQe+2gdjluqHGBRkqEvSINsU4ybjhPiVgNm/oe" +
    "0WgvEnHJTtn/90LEtHdeV/3zl2rAAAMDZKBVNL9GA7AGD0qqAQMMVGVAA7Cz+u16dl2e" +
    "EnGIet2/FEUjJba+xYqTlFsfi0ZcDrLk2w9Xuj1sVcHmXLury6b+zTWNizhGi/1zniv8" +
    "M/fP3Zo05l6vqmycB5jQIIjz1Sa+/iIXDowbyvfN2lL458T2416udqwy45KYpAtR5m+r" +
    "fMxV59r/l3ZeYq+2kq/5dbHm3EjExUspPz/OwixiJeWG8+Q/Qrzvxsqfv1QDBhgYJAOt" +
    "ovk1GoA1eFBSDRhgoCoDGoDt127t76fkSXEhz5d86+Faby3c8eDypJseO4loLkYzcOl3" +
    "H+356q2iK2NGIs54TPn5u7K1hW5UTlkBmdIUi5j14Vt7biia2yk3P1/sYoN1f5ia1KyJ" +
    "7cdVf3Z6lamrxlb88MnKx1xlxq3TF86e7/pKu3YybjpPiQ1Xzkj6+bsnrh/1Z547frpx" +
    "g3vX/gjx9zdXbkCqAQMMDJKBVtH8Gg3AGjwoqQYMMFCVAQ3A9uoWK+RSz/3bNn5xLT/r" +
    "cftsyk2r3YiTu480VupMeM0lPfmd1w6lffmOi1JS6lkkotGVMubUbYxzPnF7ZZ5SLlto" +
    "3n4451N3Jm0933LLvMo/P73MlDPY4mKfia+7yArLAclYhZuylRpCGgAAIABJREFUjTwi" +
    "6hs3T/difOsuKd7ojlj3+ymFf/bibz5U6GdGEzJlzLFaMCVmf/S2yh1INWCAgUEy0Cqa" +
    "X6MBWIMHJdWAAQaqMqAB2OYqp/1pXyxfWLwjn/Dq3jS3imZsEY3zCOsUcZ7i4q8/2PXf" +
    "Pb5Mp0TRZl00XOLW1dHi8OrdyTezJjcAP3lHZbaiMVc0YpvijA/c1NgSfnzbC4X/u5i7" +
    "BuXcv8hopqTEjjZvje2HjLk29dKcaBb28niG+KNCShRt1sU28ZPDh4s1OxPnoOQG4Cuc" +
    "8ynVgAEGGBgqvQatovk1GoA+fD58DDAwwAY0ANMv/Tiybk/Sl6ATw4cL3fLay4zzp+Ii" +
    "hrpGbA3t5uqlNb9NOxds49UzC/3cLbfNH/VnxcrRdr4Yx3mBKTH7Y9WtvonGXEoDJi6F" +
    "GX5qTeHXnx4DZ2mWnbGCOCXmffquysdcSY4batwsnnocQa/rlXqERFyaVOTnbr1z4ag/" +
    "K7ZFt7M6L86UTIlZH7qleg9SDRhgYIAMtIrm12gA1uBBSTVggIGqDGgAFq/VhNdemnwI" +
    "+rkTZ2q1CiIaM88/siJvN+KLYzR2tt69uLGKLm7Tje1msSU6Vu6t+NFTjZUqcY5WrC48" +
    "10GTMRqtcZB9N+qw+r8mJI1l842jXwISz7nItvB2t63GTbcpMfMfqj1/a9q7ruvOeZIX" +
    "8p6sEq3b3HPm8MnCJTq2eX/lY64q48bu1Ih5rNfjTP0jxKbrRr8EZM4/3tE4F7OM+exi" +
    "mbqqMlb2Vu1BqgEDDAySgVbR/BoNwBo8KKkGDDBQlQENwGJ1iq1SuyeNfqh6c0QzqE6X" +
    "fsTZVrsnb8jbidgutuLHT+WT3nRF0nvGKr6l//boi6vXEs6FG4nj2w/m0xIOqS+aq37+" +
    "TNI4oqkwmo8i57PFFteJr720rTGnntM44/3V38AZjbp2nnsdLmmoUy7/4ZNdO7Oyn3L9" +
    "pWnbatu54busXJ14E/lo7mMOipW0o8Wx5w40GsrtjPnwmt1JY065YESqAQMMMDDUcQ1a" +
    "RfNrNAB92HzYGGBggA1oABar0/b7lyZ98YmmR9zYWfXzbc52Vv5Fw6qs1VZxy3DKJQYj" +
    "cXTz/nzym68stRbRzEyJ7fct7fxW4Qt5vuBL97Y95tSt57ECr2pzRbdFF41YgTRI5/6N" +
    "ZMrK4/jDQ1yAUfWYe52Nz3RisznmxNgyXMV4V/7smVIvkSp0q3DMQV+4p+0xH920L2nM" +
    "g+hQqgEDDGQV1qBVNL9GAxBSExUDDAywAQ3A0WsUW69So+iZcXXdbhYR52hNfH255/BF" +
    "82bTDXOSv6jvnbG51C/qy37wePKZhK1+1rS/u7ZxkUWhZkMHY46VOykx5R3X1Gbl6cFl" +
    "O/NOI7YT16Wp2evLelI+L3unb6p8zL3O+CNFHE+QElGnKpvJKxJXde54aHnLnxWfiyJz" +
    "0I4HW/+MIhkrslNi8luvqtyGVAMGGBgkA62i+TUagDV4UFINGGCgKgMagOWeFRex7d4l" +
    "tfpMz/rIrckXfjS2vHZxZUysjixyVlVzxCq7st5/0dceSHrv4WfWtvxZuyeOvjU8bo2e" +
    "/JbOVjHGZTIp0e5W425kbOM+c6j4GXYviwE8928kY+tnSsSW+6rH3MuMyzvirNWUiIZ0" +
    "Ny8ZKpJxdmrqH2Ra/aw9UzYWuuU49QiHl+bJPUeTxhzN/6p9SDVggIFBMtAqml+jAViD" +
    "ByXVgAEGqjKgAdi6Nku/+2hyk2r3hHWNs5jq9JlOvbhk5xOrerItLvW8rrNHT+VT3l7O" +
    "bcrz/uWupPeOL9idfIlf9v3HOx5zNBGLRjR8q3Z30Vq1eR5gbCOuevxVZDRQUp573I48" +
    "4dWXVD7uXmVcdJN60UxckFKHlWnzPzs+adzxh4aL/Zyl33mk0H8f/551OuaUWp87frry" +
    "Gks1YICBQTPQKppfowFYgwcl1YABBqoyoAF48brEOUmpq+ai0TbhNfX68r34G2mrTI5t" +
    "faGnK2Nia2+Z52ClNA6Snu38bS/7GRPfcHl+ssCqvLK2ZEYDtGjEap+q7V0sn7tjQZ4a" +
    "sVprUFcSxWq+lNh616LKx9yrjK33RT5/zXFy95GuXCrU7srslIiLlF76Myb99eWFVuXt" +
    "mbyhlDGnrLQ8uetI5TWWasAAA4NmoFU0v0YDsAYPSqoBAwxUZUAD8OU1mf3x25OaLRFx" +
    "QcOkN14xpp9vxMKv3t/T8U1753X5uYRG67mTZ/IpJazeifPxUiIOv3/pz9h658JR/7s4" +
    "l6uMc+virLKU1ahxcUrV9i6W0SBPXbE155N3VD7uqnLfzC1JtYq5q+ox9yLjUqCjG9Mu" +
    "pDhz+GSj6Vb12JsbmKn/xrz0Z8QfREaL+Lcs3quMz27SeNfvrbzGUg0YYGDQDLSK5tdo" +
    "ANbgQUk1YICBqgxoAP55Paa/94bG6qmUOLHzUC1vO0xdYRIrGMfCqrC1v5/S8XvGNsmU" +
    "7aixtbL5v5/zj3cUasjF5Stl1Ch8pd6WW7W/i+WGq2bkqbFv9pbabavvRcZKtZSm7+E1" +
    "uysfcy8yzrZM/cNG/JEhttzW6vd43WVJv8NLV/XGrepFfMQ5tqV4fOd1Y+LfE6kGDDAw" +
    "yAZaRfNrNABr8KCkGjDAQFUGNAD/txZT3nZ1fnzbC3lKnH7heOOWzjp+hjffNDfpdynj" +
    "nLp2m65JjY5Vu0p533h2hePC/x5oH82ow6t3F9u6WlLjavZHbys+1jzPdz27rnJ/F9tW" +
    "n3qm5khE47Dq8df99vGyms11zlgJu2fq6BdeNEeYW/Lthysf+8UyViWm/B4j80nUIVYE" +
    "jhYvLN5R2hw05xO3J9V9+Kk1lddXqgEDDAyagVbR/BoNwBo8KKkGDDBQlQENwP89zy0a" +
    "SykR5yHFKoy6fn5jC1bh3+XkmUpvjY0Va4XjQt7YwtvpexZp4jXH9Pfc0Pjv1g5NHvW1" +
    "58+cy2d9uLzthgu/cl/SWJ+7fUHl/poznlfqytqXNj+igVj179GrjKZNnKFWNM6fPleL" +
    "iy26muOG8h0Pr0i2s+qXWfVjb5FFmnjNEavw4r9bd8nUQibirNOyxrroX9NuTt9yy7zK" +
    "6yvVgAEGBs1Aq2h+jQZgDR6UVAMGGKjKgAbgi2cbxQHrKRENnvhCVOfVjClbXOMyjirH" +
    "u+HKtK2hy37Q+WrF3ZM3JL3ngi/d2zjPL263HC02XT+71Pqs/NkzY3Y1WDSz9s/dmnca" +
    "0UAso/E7FnLR1x4Y8ys+y87NN6etaI7YePXMysf9Srl32qak32f+58c3/hBR5DKOsn/3" +
    "Vb96Nmmsq/+7nK3HUg0YYICBocI1aBXNr9EA9KHyoWKAgQE2MOgNwGhOxJfn1NVIZTSg" +
    "6tRA2HjtrErHu/DLvV/hFjempsSqX2T5nimjbz889tyBfELJqyk33TAnaaxLvlWfLY9h" +
    "q6w4sGDbQJwHmNqcjs971WPuZq793eirbrt1Y3g3c9s9S5J+p5U/fbpQ0/DYlgOl30if" +
    "2oBd/PUHK6+vVAMGGBg0A62i+TUagDV4UFINGGCgKgMD3QAcN5TvfGxlnhQX8nzVz5+p" +
    "fuyj5PpLpyX9Wsu+91il4029lTdWbHb6nnGZSEoU2a4XzeFuXDaw84lVSWOd/bHbKjc4" +
    "0tht99y/ujaru51x4cuFs+cL1+PknqN93RRdHSvPEgnteGh5Y36veuxlz9NF56B5n76r" +
    "9LEOP70maayzPnRL5fWVasAAA4NmoFU0v0YDsAYPSqoBAwxUZWCQG4Bb716cp0ac/1b1" +
    "uIvk9vuWJm9vrXK8cah9ypf8Y1tf6Pg9F371/rzsiLp3oz6HVgwXHkM0j8pe/dNuI+v0" +
    "/vbP/XvF8wAr9trNXH/59KR69PNZa8v/44nkBvKubO2YaYimrtSucuVjypmpcf7gyKVJ" +
    "Ug0YYICBoZ7VoFU0v0YD0IfSh5IBBgbYwKA2AFO3VI61lUd7ErcQxg2PVY/57JFTPbWY" +
    "uuqwyEqsSW+8ovS6RDOjyJlfI3F0077Kn2WMObbrFo149rF1umhEYzEajFX/nqXnuKG0" +
    "m8gv5LW9hbzTXPzNh5JWQo6cZTqWGk/T/u7avMw4OXw4n/TXl3fl83z+1NmklYpV11aq" +
    "AQMMDKKBVtH8Gg3AGjwoqQYMMFCVgUFsAK77w+g3KL40nrtz4dh6rouKP9eI6e++vvIx" +
    "n9hxMGnMsWqw0/c8feB4XlYs+XZ3zt2b8YGbksYx/MzaMddgjy3osz96W1KToR/PA1zw" +
    "xXuT6ha3Z1c95m7VIcVCw8PC7ZXeZN5unjl0Mi8runXu3swP3ZI0jp1Prq68rlINGGBg" +
    "EA20iubXaADW4EFJNWCAgaoMDFoDMC5y6NfzpJrz0MriW0Yjpv7ttZWPOQ6uT4kyVrqU" +
    "cTttxO6J67tWl2iOpcSGK2ZU+hxja3XKts3G5+t//ts1v56Y9LtGo7Fqt2Xm8FNp56yN" +
    "hfNIU3PuP/0xP3ts9Ju2myPmu26sfOtFRuOyjIitz90a4/L/fCJpLHG2YdV1lWrAAAOD" +
    "aKBVNL9GA7AGD0qqAQMMVGVgkBqAy77/ePJ5UrGaaiyuMjq8dvTD4ptj1kdurXzMqefF" +
    "TX7zlZVsBb/Y9tVubkeNM71SIlZPVfUMo5Gcsqry2Ob9+cTXXdb2DbjxeY6GY9V2y8jJ" +
    "b7kyadVbbAsfq02vVhnz0JmDJ/KUOLJhb6N2VY+93YwzHDuNWEUYRxrU5UzZ+Z8r/yIk" +
    "qQYMMMDA0Kg1aBXNr9EA9GHyYWKAgQE2MCgNwGgSxMHkqTfN1uEyhXYytgamxPzPV/+F" +
    "LfW8rzLO+lr4lfvyTiNWlXazLkVu/hyJMF7VNsjGuX/ztyWNdfbHX3725KQ3XZGfGD5c" +
    "+OecfuF44yy1qv12mmt/NzlPibjBvOoxl5kz3n9jfmrv0aQaHN9+cMyfBbnoXzu/CGTl" +
    "T5/u6hiPbtxXeCznTp4Zs/9uSjVggIFsjNegVTS/RgOwBg9KqgEDDFRlYBAagAu+cE9+" +
    "LvU8qQXbxuR5UiMZzcuUWPKdRyodb6xkSoloFpbxvrH67PyZtMZwc8T2vW5uD5/y1quS" +
    "Vq02xlPRM9x889yk2q35zcSWP2v+Z8fnF84VbwjHmZdlnAlZZcZKtpSIea3qMZeV0cA9" +
    "8fyhpN//5K4jtTi7tIy5L8X6S2P/vK3dnYPecU3SHNQYTw3qKtWAAQYG0UCraH6NBmAN" +
    "HpRUAwYYqMpAvzcA53zqzoE6T2okdz27Lul3jotRqhzv7I/dljTeU/uOVbZaciRiu2a3" +
    "b2Bd+dNnksa06brZlTy/RV97IKlJsGfKxlGbFhuvnpn0u0cDskrDneS8T9+V9LvGhTlj" +
    "7VzSV2pyx1bwlIht5jP//ubKx17Vma3Nq+1i5WQ3x7bql1nSmOJzW3U9pRowwMCgGmgV" +
    "za/RAKzBg5JqwAADVRno5wbgrA/dkp8esPOkRnLLrfOTfu/hp9dUOt7YwpYSB5ftLO29" +
    "49KMdmLDld2/bGPP1I1JY5r7qTt7/uymvfO6pM/Zyd1H8slvvarYluKECxKiARmNyCod" +
    "t5s7Hl4xkE2WSW+8Ij+8enfymZsX2zo+ljO12T0S6y/r/mUbe2dsThrTnE/017ORasAA" +
    "A9kYqkGraH6NBmANHpRUAwYYqMpAvzYAp7+vjfOktr0w5s+TGsnV/zUheUVNlZed7Hxi" +
    "VdJ447bUst57xgduylPjyPq9pZxB+Eo55e1XJ21Pji2UvV4VFttuU1ZQRpMuZetqbA1N" +
    "aS7Ga6MhWZXjdjJWG8fcmlLDftj6GtvvX1hc/N+fkYtP5v3LXZWPveyc+aFb8tSIi566" +
    "ve09/j1MOZs1/g2tupZSDRhgYJANtIrm12gA1uBBSTVggIGqDPRjAzBuIo0tcoN4nlS7" +
    "WwqrvLlxwqsvaVzkkBLrLpla2UUbvbj4IzJW96TEltvm136l6abr07coL/7mQ3mecHl3" +
    "NCTH0nmAqVss988d+2esxWd+38wtSb93XBoTl/ZUPfY6XLTRi4s/ImOV86Bsw5dqwAAD" +
    "WR/UoFU0v0YDsAYPSqoBAwxUZaDfGoCxtfDopn0DfZ7UyBfsOKMuJWIVXhVjXfa9x/LU" +
    "iAZnmWNI3QYc2xa7udounl/KTbgRcd5lL5/b4m+kNeZirmm3Mbf17sVJtYjGZBWW28lD" +
    "q3Yl/W7L//OJysfcScZK49QzSuOSjCXffrjysddpG/ChFcNdHU/c5Bt/GEuJftuaLdWA" +
    "AQayMVaDVtH8Gg3AGjwoqQYMMFCVgX5qAMZWusOJX6bPHD7Zt19a4ibjlIitXrEdtqfj" +
    "HDeUH16TeAbYsdONBlnZN13GCqOUWNrFm5PX/HZS0liiidTL5zbt3dfnZxK25sbnLP6b" +
    "TpoRSas0L+SNBmVPLbeRMfeknn83lm8nj8976nmHseV5+Q+frH7sXc7Ybpt6I3msju3W" +
    "eNYOTa7sXFapBgwwwMBQWzVoFc2v0QD0AfMBY4CBATbQLw3A+FKccmHAyO/Tj+dJjeTq" +
    "/047BzBi7/RNPR3jih8/lTzGbq1U3Pl42jmEJ4cPd+W26LiE5vT+Y0lj6WWDJM4+jC/7" +
    "KbH0u492/L6xSjfOgCsa0aDspOnYi9w2Pm1l4/b7l1Y+5k5y650Lk37faOTGPFb1uHuV" +
    "cbZpSpzYeSif+IbLu3Izc+qxDMu+/3jl9ZNqwAADg26gVTS/RgOwBg9KqgEDDFRloB8a" +
    "gNGQSL2pMLbHLvxy/54nFTnlbVc3ts6lxupfPduT8cWZi7GiKTUWf/3BrownttCmxo4H" +
    "lpU+jriROSVO7TtW+orIV8rnEps420usUTu3RXf7spZO/mgRKyNTYu4//7HycbebG6+d" +
    "ldfxltuxfnbrtnuXlD6O1C3aJ/ccre3nTKoBAwwMkoFW0fwaDcAaPCipBgwwUJWBsd4A" +
    "jPOkhp9Zm6fEIJwnNZLDT65Oqk2jPmfP5wu/en9XxzXpTVckH3ofcey5A129rTi1kRyx" +
    "qsSGaTurNtf+bnLPPMXnJuXcvziPs+wtq6mrpKJh2av6pOSKH6Wtfj26eX/lY243w2hq" +
    "bL5pMC+U2D/nueRarfzZM5UdPxCx5jcTK6+bVAMGGGBgqOU83VwbDUAfFh8WBhgYYANj" +
    "ugEY50k9uDzpi8qgnCc1krM+cmtSw2Yk4jy8pf/+WNduaT6yfm/6oBo3Xz7T3Xp9+NaG" +
    "kdSGaRlbXKPeqe99fNsLPVv9N/09NyStWDt36mzDX9njiG3Xx7cn3PJ9Ia9lw/+FRcXn" +
    "3m7cfN2rjM9s6hwUW6OrHneV50KmzgNxduCSEs4kXfaDx5Pfu/FHGav/Kncj1YABBjIN" +
    "QAhMBAww0J8G4gv/9PfdWEqmXJpx7uSZ0t633dtAm3PLLfPydrZszvnkHbXNWBlX9dl2" +
    "f4oLeb71rkX5xNdfVtpYohGTerbUSMQlEGW4GS1Tm8qNUp2/8OJKvHZuBh43lK+/dFry" +
    "F++IMhqPReecQyuHk8bWzbPb5n7qzqQLE6JxGQ3MXtSq6HmGKU2xWLUcl0RUPe52Pu+p" +
    "rmPbdmzHr3oubpXT3nld1+v2/CNpF6U0jJy/0Fi91/YcdPn0tuagOjbXpRowwMCgGmgV" +
    "za+xArAGD0qqAQMMpBiY9aFb8rEeZRzOH9sL+y3KWMVx0QPdE25svdj5Tmt+PbH9w+bH" +
    "DeULvnRvvn/u1rbHEF9Me3X+WdQrztVrJw7M39ZYRVj0veZ84vb8hcVpK8FGYs/Uje19" +
    "2W8joxGcErsnre/6mGJFXEpEA7OXZyW+Um65bX7S2PdO6+3lPGVl/MGl3yKeXbfrNuXt" +
    "VydfBDQSMc/O/NAthd8rmpoHlz7f1nvtnryhcmNSDRhggIGhP9WgVTTXSAPQh8aHhgEG" +
    "xpgBDcAX66ABWNzM0u880tZW4OY4e+x047zFFT95uvEFc0KLs93ijL5p77ouX/Kthxvn" +
    "ryVt12wRm26Y09PPWJyB2Ha9LuSNc7xW/SJrrPRqXrU44TWXNJp+sVKn3S/dEdGgjEte" +
    "elGLpf/2aFItTu460rjJuOtjGzeU75u9Jalu0cisev6OJuTpA2mrYOPzW/W420kNwPZr" +
    "F5cddTIHxWdj1c+fyWd+8KaXz0H/eMeLc1Dibd4v/cPQ5LdeVbkxqQYMMMDA0J9q0Cqa" +
    "a6QB6EPjQ8MAA2PMgAbgi3XQAExzE020suPciTP5ieHD+eE1uxvn0bVzq+9osXf6pq5e" +
    "/NEqtybedvtKcfboqUatyohYDdntS1pGMrbrpzzTGNv8z43v2TOa8o5r0lZrXsgbDc0q" +
    "5+846zElYsv8WD1jTQOws/ptvXtxXss56Nz5xqruqn1JNWCAAQaG/qwGraL5NRqAPjg+" +
    "OAwwMMYMaAC+WAcNwDQ30UTb8XD62VJVRlxSE5c+VPE5i3rtmbwhr1uUeevwK2WsFDq8" +
    "enfS2DZeO6vnzymaoSlnl0VDMxqbVc3fyasWa3qLcZHUAOysfrFyL7Z/1you5I2VhVXb" +
    "kmrAAAMMDL2sBq2i+TUagD48PjwMMDDGDGgAvlgHDcA2vlD+5e/z7WPkXK4DC7e3f+5g" +
    "SRnbnFNva+1mbLx6Zs9+9233LEkaW9SpipWa7VwIFI3NaHD2epzT33198kULsz96W6Wf" +
    "gU5SA7DzGk587aUdHRdQdmy4YkblrqQaMMAAA0MXrUGraH6NBqAPkA8QAwyMMQMagC/W" +
    "QQOwfUOxiuzC2fN5XSMaB3W5sCGakHumbKy2IBfyfNN1s3v2Oy/7Xto21cYtuyVc7NPJ" +
    "SqnU88y2jV/c83GmbsOPW9qr9t9JagCWNwdVvRIwGtdxU3DVpqQaMMAAA0Mta9Aqml+j" +
    "AehD5EPEAANjzIAG4It10ADszFGc1Rbn9tUp4ryz5f/xROWfsZdmrGwr80zAlDh3/HTj" +
    "QpVe/a4zPnBT48KXqm+vbuu8wqNpZ1BGo7OXhk7uPpI0vjW/mVh5XTtJDcBy/ZR5JmBK" +
    "xHyw+BsPVe5JqgEDDDAw9Io1aBXNr9EA9EHyQWKAgTFmQAPwxTpoAJazxXXT9bNLOxy+" +
    "k9UlcT5h3W+VXPzNhxq33PYq9s/b2mjI9dLD4bV7ksa47d4llT+XkVz2/ceTGxu9qm/j" +
    "VteEOH/qbG9uU+5iagCWX9Ml3344uZHcScSN5lWemSnVgAEGGBgqXINW0fwaDUAfKh8q" +
    "BhgYYwY0AF+sgwZgeaamvP3qxjlqqSu/Oo3zp8/lzz+yoqdNrk4zLiV57s6F+bmT3Wua" +
    "xs3KK3/6dJ6N6+3vtv3+pUnjPLJhb6NpWPUzac7Ui26i4dmL3yH1Qpld2drKa9nxsxgj" +
    "542mxJbb5tdiDtr6x0XdnYN2HspX/Oipyn9XqQYMMMDAUOEatIrm12gA+lD5UDHAwBgz" +
    "EGdt7Z+7dUxnNJzK+KJf9e9Rds77zN2V2pr4usvy5T98snFTaTTnurXa79CK4XzNbyfV" +
    "fsXfK2WMPS7lOLX3aGm1ObRyOF/2g8cbZ9r1+veZ/bHbkr3GHyOqfg4vM/z6y/LdE9cn" +
    "/R4rfvhkd8f02kvzfbO2JI1p/ufHV17LTnPt0OTK59Sys1e3cBfJKTEHXTMrP7XvWGlz" +
    "0MHlOxtb46uYg6QaMMAAA0Md1aBVNL9GA9AHzQeNAQYYYICBizZSFn3tgXzLrfMb28Da" +
    "/ZJ59sipxg2xcelCfLEcy02/Vmdzzf2nP+abb5zbaGzGmX1FI2q6b+aWxllvVV6iIdWA" +
    "gTE+B/3zH/PNN81t/BEhdQ7aO2NzvubXE/Np5qDKn6VUAwYYyDqoQatofo0GIGQmGgYY" +
    "YIABBgoZmPzmK/NZH741X/jV+xurpmI1TKzki9shY7VP/L9j62qcdzb747fnU95xzeDZ" +
    "GjeUT3/PDY0aRcNz1S+zfN3vpzTqFLVZ+t1HGys9x/r5blINGBgjc9Cvns3X/WHqy+eg" +
    "N5uDKn9WUg0YYOBV5dVAA9AHygeKAQYYYIABBhhggAEGGGCAAQYYYOBV/VsDDcAaPASp" +
    "BgwwwAADDDDAAAMMMMAAAwwwwAADmQYgBCYCBhhggAEGGGCAAQYYYIABBhhggAEGMisA" +
    "ITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkNkCDIGJgAEGGGCAAQYYYIABBhhggAEGGGCg" +
    "/w04A7AGD0GqAQMMMMAAAwwwwAADDDDAAAMMMMBApgEIgYmAAQYYYIABBhhggAEGGGCA" +
    "AQYYYICBzApACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMMZLYAQ2AiYIABBhhggAEGGGCA" +
    "AQYYYIABBhjofwPOAKzBQ5BqwAADDDDAAAMMMMAAAwwwwAADDDCQaQBCYCJggAEGGGCA" +
    "AQYYYIABBhhggAEGGGAgswIQAhMBAwwwwAADDDDAAAMMMMAAAwwwwAADmS3AEJgIGGCA" +
    "AQYYYIABBhhggAEGGGCAAQb634AzAGvwEKQaMMAAAwwwwAADDDDAAAMMMMAAAwxkGoAQ" +
    "mAgYYIABBhhggAEGGGCAAQYYYIABBhjIrACEwETAAAMMMMAAAwwwwAADDDDAAAMMMMBA" +
    "ZgswBCYCBhhggAEGGGCAAQYYYIABBhhggIH+N+AMwBo8BKkGDDDAAAMMMMAAAwwwwAAD" +
    "DDDAAAOZBiAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyKwAhMBEwwAADDDDAAAMMMMAA" +
    "AwwwwAADDDCQ2QIMgYmAAQYYYIABBhhggAEGGGCAAQYYYKD/DTgDsAYPQaoBAwwwwAAD" +
    "DDDAAAMMMMAAAwwwwECmAQiBiYABBhhggAEGGGCAAQYYYIABBhhggIHMCkAITAQMMMAA" +
    "AwwwwAADDDDAAAMMMMAAAwxktgBDYCJggAEGGGCAAQYYYIABBhhggAEGGOh/A84ArMFD" +
    "kGrAAAMMMMAAAwwwwAADDDDAAAMMMJBpAEJgImCAAQYYYIABBhhggAEGGGCAAQYYYCCz" +
    "AhACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZLcCtQTSDAAAegklEQVQQmAgYYIABBhhg" +
    "gAEGGGCAAQYYYIABBvrfgDMAa/AQpBowwAADDDDAAAMMMMAAAwwwwAADDGQagBCYCBhg" +
    "gAEGGGCAAQYYYIABBhhggAEGGMisAITARMAAAwwwwAADDDDAAAMMMMAAAwwwwEBmCzAE" +
    "JgIGGGCAAQYYYIABBhhggAEGGGCAgf434AzAGjwEqQYMMMAAAwwwwAADDDDAAAMMMMAA" +
    "A5kGIAQmAgYYYIABBhhggAEGGGCAAQYYYIABBjIrACEwETDAAAMMMMAAAwwwwAADDDDA" +
    "AAMMMJDZAgyBiYABBhhggAEGGGCAAQYYYIABBhhgoP8NOAOwBg9BqgEDDDDAAAMMMMAA" +
    "AwwwwAADDDDAQKYBCIGJgAEGGGCAAQYYYIABBhhggAEGGGCAgcwKQAhMBAwwwAADDDDA" +
    "AAMMMMAAAwwwwAADDGS2AENgImCAAQYYYIABBhhggAEGGGCAAQYY6H8DzgCswUOQasAA" +
    "AwwwwAADDDDAAAMMMMAAAwwwkGkAQmAiYIABBhhggAEGGGCAAQYYYIABBhhgILMCEAIT" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMAAA5ktwBCYCBhggAEGGGCAAQYYYIABBhhggAEG+t+A" +
    "MwBr8BCkGjDAAAMMMMAAAwwwwAADDDDAAAMMZBqAEJgIGGCAAQYYYIABBhhggAEGGGCA" +
    "AQYYyKwAhMBEwAADDDDAAAMMMMAAAwwwwAADDDDAQGYLMAQmAgYYYIABBhhggAEGGGCA" +
    "AQYYYICB/jfgDMAaPASpBgwwwAADDDDAAAMMMMAAAwwwwAADmQYgBCYCBhhggAEGGGCA" +
    "AQYYYIABBhhggAEGMisAITARMMAAAwwwwAADDDDAAAMMMMAAAwwwkNkCDIGJgAEGGGCA" +
    "AQYYYIABBhhggAEGGGCg/w04A7AGD0GqAQMMMMAAAwwwwAADDDDAAAMMMMBApgEIgYmA" +
    "AQYYYIABBhhggAEGGGCAAQYYYICBzApACEwEDDDAAAMMMMAAAwwwwAADDDDAAAMMZLYA" +
    "Q2AiYIABBhhggAEGGGCAAQYYYIABBhjofwPOAKzBQ5BqwAADDDDAAAMMMMAAAwwwwAAD" +
    "DDCQaQBCYCJggAEGGGCAAQYYYIABBhhggAEGGGAgswIQAhMBAwwwwAADDDDAAAMMMMAA" +
    "AwwwwAADmS3AEJgIGGCAAQYYYIABBhhggAEGGGCAAQb634AzAGvwEKQaMMAAAwwwwAAD" +
    "DDDAAAMMMMAAAwxkGoAQmAgYYIABBhhggAEGGGCAAQYYYIABBhjIrACEwETAAAMMMMAA" +
    "AwwwwAADDDDAAAMMMMBAZgswBCYCBhhggAEGGGCAAQYYYIABBhhggIH+N+AMwBo8BKkG" +
    "DDDAAAMMMMAAAwwwwAADDDDAAAOZBiAEJgIGGGCAAQYYYIABBhhggAEGGGCAAQYyKwAh" +
    "MBEwwAADDDDAAAMMMMAAAwwwwAADDDCQ2QIMgYmAAQYYYIABBhhggAEGGGCAAQYYYKD/" +
    "DTgDsAYPQaoBAwwwwAADDDDAAAMMMMAAAwwwwECmAQiBiYABBhhggAEGGGCAAQYYYIAB" +
    "BhhggIHMCkAITAQMMMAAAwwwwAADDDDAAAMMMMAAAwxktgBDYCJggAEGGGCAAQYYYIAB" +
    "BhhggAEGGOh/A84ArMFDkGrAAAMMMMAAAwwwwAADDDDAAAMMMJBpAEJgImCAAQYYYIAB" +
    "BhhggAEGGGCAAQYYYCCzAhACEwEDDDDAAAMMMMAAAwwwwAADDDDAAAOZLcAQmAgYYIAB" +
    "BhhggAEGGGCAAQYYYIABBvrfgDMAa/AQpBowwAADDDDAAAMMMMAAAwwwwAADDGQagBCY" +
    "CBhggAEGGGCAAQYYYIABBhhggAEGGMisAITARMAAAwwwwAADDDDAAAMMMMAAAwwwwEBm" +
    "CzAEJgIGGGCAAQYYYIABBhhggAEGGGCAgf434AzAGjwEqQYMMMAAAwwwwAADDDDAAAMM" +
    "MMAAA/+/nTs4YSiGgSjYfyp65aWGQA76+0egBuRhD8J2FoAQCAIGGGCAAQYYYIABBhhg" +
    "gAEGGGCAAQZyAxACQcAAAwwwwAADDDDAAAMMMMAAAwwwwECeAEMgCBhggAEGGGCAAQYY" +
    "YIABBhhggAEG9g34A/DAIWgzYIABBhhggAEGGGCAAQYYYIABBhjIAhACQcAAAwwwwAAD" +
    "DDDAAAMMMMAAAwwwwEBuAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgTYAgEAQMMMMAA" +
    "AwwwwAADDDDAAAMMMMDAvgF/AB44BG0GDDDAAAMMMMAAAwwwwAADDDDAAANZAEIgCBhg" +
    "gAEGGGCAAQYYYIABBhhggAEGGMgNQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA3kCDIEg" +
    "YIABBhhggAEGGGCAAQYYYIABBhjYN+APwAOHoM2AAQYYYIABBhhggAEGGGCAAQYYYCAL" +
    "QAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA7kBCIEgYIABBhhggAEGGGCAAQYYYIABBhhg" +
    "IE+AIRAEDDDAAAMMMMAAAwwwwAADDDDAAAP7BvwBeOAQtBkwwAADDDDAAAMMMMAAAwww" +
    "wAADDGQBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIDcAIRAEDDDAAAMMMMAAAwwwwAAD" +
    "DDDAAAMM5AkwBIKAAQYYYIABBhhggAEGGGCAAQYYYGDfgD8ADxyCNgMGGGCAAQYYYIAB" +
    "BhhggAEGGGCAgSwAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AYgBIKAAQYYYIABBhhg" +
    "gAEGGGCAAQYYYICBPAGGQBAwwAADDDDAAAMMMMAAAwwwwAADDOwb8AfggUPQZsAAAwww" +
    "wAADDDDAAAMMMMAAAwwwkAUgBIKAAQYYYIABBhhggAEGGGCAAQYYYICB3ACEQBAwwAAD" +
    "DDDAAAMMMMAAAwwwwAADDDCQJ8AQCAIGGGCAAQYYYIABBhhggAEGGGCAgX0D/gA8cAja" +
    "DBhggAEGGGCAAQYYYIABBhhggAEGsgCEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQG4AQ" +
    "CAIGGGCAAQYYYIABBhhggAEGGGCAAQbyBBgCQcAAAwwwwAADDDDAAAMMMMAAAwwwsG/A" +
    "H4AHDkGbAQMMMMAAAwwwwAADDDDAAAMMMMBAFoAQCAIGGGCAAQYYYIABBhhggAEGGGCA" +
    "AQZyAxACQcAAAwwwwAADDDDAAAMMMMAAAwwwwECeAEMgCBhggAEGGGCAAQYYYIABBhhg" +
    "gAEG9g34A/DAIWgzYIABBhhggAEGGGCAAQYYYIABBhjIAhACQcAAAwwwwAADDDDAAAMM" +
    "MMAAAwwwwEBuAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgTYAgEAQMMMMAAAwwwwAAD" +
    "DDDAAAMMMMDAvgF/AB44BG0GDDDAAAMMMMAAAwwwwAADDDDAAANZAEIgCBhggAEGGGCA" +
    "AQYYYIABBhhggAEGGMgNQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA3kCDIEgYIABBhhg" +
    "gAEGGGCAAQYYYIABBhjYN+APwAOHoM2AAQYYYIABBhhggAEGGGCAAQYYYCALQAgEAQMM" +
    "MMAAAwwwwAADDDDAAAMMMMAAA7kBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIE+AIRAE" +
    "DDDAAAMMMMAAAwwwwAADDDDAAAP7BvwBeOAQtBkwwAADDDDAAAMMMMAAAwwwwAADDGQB" +
    "CIEgYIABBhhggAEGGGCAAQYYYIABBhhgIDcAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM" +
    "5AkwBIKAAQYYYIABBhhggAEGGGCAAQYYYGDfgD8ADxyCNgMGGGCAAQYYYIABBhhggAEG" +
    "GGCAgSwAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AYgBIKAAQYYYIABBhhggAEGGGCA" +
    "AQYYYICBPAGGQBAwwAADDDDAAAMMMMAAAwwwwAADDOwb8AfggUPQZsAAAwwwwAADDDDA" +
    "AAMMMMAAAwwwkAUgBIKAAQYYYIABBhhggAEGGGCAAQYYYICB3ACEQBAwwAADDDDAAAMM" +
    "MMAAAwwwwAADDDCQJ8AQCAIGGGCAAQYYYIABBhhggAEGGGCAgX0D/gA8cAjaDBhggAEG" +
    "GGCAAQYYYIABBhhggAEGsgCEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQG4AQCAIGGGCA" +
    "AQYYYIABBhhggAEGGGCAAQbyBBgCQcAAAwwwwAADDDDAAAMMMMAAAwwwsG/AH4AHDkGb" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMBAFoAQCAIGGGCAAQYYYIABBhhggAEGGGCAAQZyAxAC" +
    "QcAAAwwwwAADDDDAAAMMMMAAAwwwwECeAEMgCBhggAEGGGCAAQYYYIABBhhggAEG9g34" +
    "A/DAIWgzYIABBhhggAEGGGCAAQYYYIABBhjIAhACQcAAAwwwwAADDDDAAAMMMMAAAwww" +
    "wEBuAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgTYAgEAQMMMMAAAwwwwAADDDDAAAMM" +
    "MMDAvgF/AB44BG0GDDDAAAMMMMAAAwwwwAADDDDAAANZAEIgCBhggAEGGGCAAQYYYIAB" +
    "BhhggAEGGMgNQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA3kCDIEgYIABBhhggAEGGGCA" +
    "AQYYYIABBhjYN+APwAOHoM2AAQYYYIABBhhggAEGGGCAAQYYYCALQAgEAQMMMMAAAwww" +
    "wAADDDDAAAMMMMAAA7kBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIE+AIRAEDDDAAAMM" +
    "MMAAAwwwwAADDDDAAAP7BvwBeOAQtBkwwAADDDDAAAMMMMAAAwwwwAADDGQBCIEgYIAB" +
    "BhhggAEGGGCAAQYYYIABBhhgIDcAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AkwBIKA" +
    "AQYYYIABBhhggAEGGGCAAQYYYGDfgD8ADxyCNgMGGGCAAQYYYIABBhhggAEGGGCAgSwA" +
    "IRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AYgBIKAAQYYYIABBhhggAEGGGCAAQYYYICB" +
    "PAGGQBAwwAADDDDAAAMMMMAAAwwwwAADDOwb8AfggUPQZsAAAwwwwAADDDDAAAMMMMAA" +
    "AwwwkAUgBIKAAQYYYIABBhhggAEGGGCAAQYYYICB3ACEQBAwwAADDDDAAAMMMMAAAwww" +
    "wAADDDCQJ8AQCAIGGGCAAQYYYIABBhhggAEGGGCAgX0D/gA8cAjaDBhggAEGGGCAAQYY" +
    "YIABBhhggAEGsgCEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQG4AQCAIGGGCAAQYYYIAB" +
    "BhhggAEGGGCAAQbyBBgCQcAAAwwwwAADDDDAAAMMMMAAAwwwsG/AH4AHDkGbAQMMMMAA" +
    "AwwwwAADDDDAAAMMMMBAFoAQCAIGGGCAAQYYYIABBhhggAEGGGCAAQZyAxACQcAAAwww" +
    "wAADDDDAAAMMMMAAAwwwwECeAEMgCBhggAEGGGCAAQYYYIABBhhggAEG9g34A/DAIWgz" +
    "YIABBhhggAEGGGCAAQYYYIABBhjIAhACQcAAAwwwwAADDDDAAAMMMMAAAwwwwEBuAEIg" +
    "CBhggAEGGGCAAQYYYIABBhhggAEGGMgTYAgEAQMMMMAAAwwwwAADDDDAAAMMMMDAvgF/" +
    "AB44BG0GDDDAAAMMMMAAAwwwwAADDDDAAANZAEIgCBhggAEGGGCAAQYYYIABBhhggAEG" +
    "GMgNQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA3kCDIEgYIABBhhggAEGGGCAAQYYYIAB" +
    "BhjYN+APwAOHoM2AAQYYYIABBhhggAEGGGCAAQYYYCALQAgEAQMMMMAAAwwwwAADDDDA" +
    "AAMMMMAAA7kBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIE+AIRAEDDDAAAMMMMAAAwww" +
    "wAADDDDAAAP7BvwBeOAQtBkwwAADDDDAAAMMMMAAAwwwwAADDGQBCIEgYIABBhhggAEG" +
    "GGCAAQYYYIABBhhgIDcAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AkwBIKAAQYYYIAB" +
    "BhhggAEGGGCAAQYYYGDfgD8ADxyCNgMGGGCAAQYYYIABBhhggAEGGGCAgSwAIRAEDDDA" +
    "AAMMMMAAAwwwwAADDDDAAAMM5AYgBIKAAQYYYIABBhhggAEGGGCAAQYYYICBPAGGQBAw" +
    "wAADDDDAAAMMMMAAAwwwwAADDOwb8AfggUPQZsAAAwwwwAADDDDAAAMMMMAAAwwwkAUg" +
    "BIKAAQYYYIABBhhggAEGGGCAAQYYYICB3ACEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQ" +
    "J8AQCAIGGGCAAQYYYIABBhhggAEGGGCAgX0D/gA8cAjaDBhggAEGGGCAAQYYYIABBhhg" +
    "gAEGsgCEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQG4AQCAIGGGCAAQYYYIABBhhggAEG" +
    "GGCAAQbyBBgCQcAAAwwwwAADDDDAAAMMMMAAAwwwsG/AH4AHDkGbAQMMMMAAAwwwwAAD" +
    "DDDAAAMMMMBAFoAQCAIGGGCAAQYYYIABBhhggAEGGGCAAQZyAxACQcAAAwwwwAADDDDA" +
    "AAMMMMAAAwwwwECeAEMgCBhggAEGGGCAAQYYYIABBhhggAEG9g34A/DAIWgzYIABBhhg" +
    "gAEGGGCAAQYYYIABBhjIAhACQcAAAwwwwAADDDDAAAMMMMAAAwwwwEBuAEIgCBhggAEG" +
    "GGCAAQYYYIABBhhggAEGGMgTYAgEAQMMMMAAAwwwwAADDDDAAAMMMMDAvgF/AB44BG0G" +
    "DDDAAAMMMMAAAwwwwAADDDDAAANZAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgNQAgE" +
    "AQMMMMAAAwwwwAADDDDAAAMMMMAAA3kCDIEgYIABBhhggAEGGGCAAQYYYIABBhjYN+AP" +
    "wAOHoM2AAQYYYIABBhhggAEGGGCAAQYYYCALQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAA" +
    "A7kBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIE+AIRAEDDDAAAMMMMAAAwwwwAADDDDA" +
    "AAP7BvwBeOAQtBkwwAADDDDAAAMMMMAAAwwwwAADDGQBCIEgYIABBhhggAEGGGCAAQYY" +
    "YIABBhhgIDcAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AkwBIKAAQYYYIABBhhggAEG" +
    "GGCAAQYYYGDfgD8ADxyCNgMGGGCAAQYYYIABBhhggAEGGGCAgSwAIRAEDDDAAAMMMMAA" +
    "AwwwwAADDDDAAAMM5AYgBIKAAQYYYIABBhhggAEGGGCAAQYYYICBPAGGQBAwwAADDDDA" +
    "AAMMMMAAAwwwwAADDOwb8AfggUPQZsAAAwwwwAADDDDAAAMMMMAAAwwwkAUgBIKAAQYY" +
    "YIABBhhggAEGGGCAAQYYYICB3ACEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQJ8AQCAIG" +
    "GGCAAQYYYIABBhhggAEGGGCAgX0D/gA8cAjaDBhggAEGGGCAAQYYYIABBhhggAEGsgCE" +
    "QBAwwAADDDDAAAMMMMAAAwwwwAADDDCQG4AQCAIGGGCAAQYYYIABBhhggAEGGGCAAQby" +
    "BBgCQcAAAwwwwAADDDDAAAMMMMAAAwwwsG/AH4AHDkGbAQMMMMAAAwwwwAADDDDAAAMM" +
    "MMBAFoAQCAIGGGCAAQYYYIABBhhggAEGGGCAAQZyAxACQcAAAwwwwAADDDDAAAMMMMAA" +
    "AwwwwECeAEMgCBhggAEGGGCAAQYYYIABBhhggAEG9g34A/DAIWgzYIABBhhggAEGGGCA" +
    "AQYYYIABBhjIAhACQcAAAwwwwAADDDDAAAMMMMAAAwwwwEBuAEIgCBhggAEGGGCAAQYY" +
    "YIABBhhggAEGGMgTYAgEAQMMMMAAAwwwwAADDDDAAAMMMMDAvgF/AB44BG0GDDDAAAMM" +
    "MMAAAwwwwAADDDDAAANZAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgNQAgEAQMMMMAA" +
    "AwwwwAADDDDAAAMMMMAAA3kCDIEgYIABBhhggAEGGGCAAQYYYIABBhjYN+APwAOHoM2A" +
    "AQYYYIABBhhggAEGGGCAAQYYYCALQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA7kBCIEg" +
    "YIABBhhggAEGGGCAAQYYYIABBhhgIE+AIRAEDDDAAAMMMMAAAwwwwAADDDDAAAP7BvwB" +
    "eOAQtBkwwAADDDDAAAMMMMAAAwwwwAADDGQBCIEgYIABBhhggAEGGGCAAQYYYIABBhhg" +
    "IDcAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM5AkwBIKAAQYYYIABBhhggAEGGGCAAQYY" +
    "YGDfgD8ADxyCNgMGGGCAAQYYYIABBhhggAEGGGCAgSwAIRAEDDDAAAMMMMAAAwwwwAAD" +
    "DDDAAAMM5AYgBIKAAQYYYIABBhhggAEGGGCAAQYYYICBPAGGQBAwwAADDDDAAAMMMMAA" +
    "AwwwwAADDOwb8AfggUPQZsAAAwwwwAADDDDAAAMMMMAAAwwwkAUgBIKAAQYYYIABBhhg" +
    "gAEGGGCAAQYYYICB3ACEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQJ8AQCAIGGGCAAQYY" +
    "YIABBhhggAEGGGCAgX0D/gA8cAjaDBhggAEGGGCAAQYYYIABBhhggAEGsgCEQBAwwAAD" +
    "DDDAAAMMMMAAAwwwwAADDDCQG4AQCAIGGGCAAQYYYIABBhhggAEGGGCAAQbyBBgCQcAA" +
    "AwwwwAADDDDAAAMMMMAAAwwwsG/AH4AHDkGbAQMMMMAAAwwwwAADDDDAAAMMMMBAFoAQ" +
    "CAIGGGCAAQYYYIABBhhggAEGGGCAAQZyAxACQcAAAwwwwAADDDDAAAMMMMAAAwwwwECe" +
    "AEMgCBhggAEGGGCAAQYYYIABBhhggAEG9g34A/DAIWgzYIABBhhggAEGGGCAAQYYYIAB" +
    "BhjIAhACQcAAAwwwwAADDDDAAAMMMMAAAwwwwEBuAEIgCBhggAEGGGCAAQYYYIABBhhg" +
    "gAEGGMgTYAgEAQMMMMAAAwwwwAADDDDAAAMMMMDAvgF/AB44BG0GDDDAAAMMMMAAAwww" +
    "wAADDDDAAANZAEIgCBhggAEGGGCAAQYYYIABBhhggAEGGMgNQAgEAQMMMMAAAwwwwAAD" +
    "DDDAAAMMMMAAA3kCDIEgYIABBhhggAEGGGCAAQYYYIABBhjYN+APwAOHoM2AAQYYYIAB" +
    "BhhggAEGGGCAAQYYYCALQAgEAQMMMMAAAwwwwAADDDDAAAMMMMAAA7kBCIEgYIABBhhg" +
    "gAEGGGCAAQYYYIABBhhgIE+AIRAEDDDAAAMMMMAAAwwwwAADDDDAAAP7BvwBeOAQtBkw" +
    "wAADDDDAAAMMMMAAAwwwwAADDGQBCIEgYIABBhhggAEGGGCAAQYYYIABBhhgIDcAIRAE" +
    "DDDAAAMMMMAAAwwwwAADDDDAAAMM5AkwBIKAAQYYYIABBhhggAEGGGCAAQYYYGDfgD8A" +
    "DxyCNgMGGGCAAQYYYIABBhhggAEGGGCAgSwAIRAEDDDAAAMMMMAAAwwwwAADDDDAAAMM" +
    "5AYgBIKAAQYYYIABBhhggAEGGGCAAQYYYICBPAGGQBAwwAADDDDAAAMMMMAAAwwwwAAD" +
    "DOwb8AfggUPQZsAAAwwwwAADDDDAAAMMMMAAAwwwkAUgBIKAAQYYYIABBhhggAEGGGCA" +
    "AQYYYICB3ACEQBAwwAADDDDAAAMMMMAAAwwwwAADDDCQJ8AQCAIGGGCAAQYYYIABBhhg" +
    "gAEGGGCAgX0D/gA8cAjaDBhggAEGGGCAAQYYYIABBhhggAEGsgCEQBAwwAADDDDAAAMM" +
    "MMAAAwwwwAADDDCQG4AQCAIGGGCAAQYYYIABBhhggAEGGGCAAQbyBBgCQcAAAwwwwAAD" +
    "DDDAAAMMMMAAAwwwsG/AH4AHDkGbAQMMMMAAAwwwwAADDDDAAAMMMMBAFoAQCAIGGGCA" +
    "AQYYYIABBhhggAEGGGCAAQZyAxACQcAAAwwwwAADDDDAAAMMMMAAAwwwwECeAEMgCBhg" +
    "gAEGGGCAAQYYYIABBhhggAEG9g387Q9ApZRSSimllFJKKaXUc8oCUCmllFJKKaWUUkqp" +
    "4bIAVEoppZRSSimllFJquCwAlVJKKaWUUkoppZQaLgtApZRSSimllFJKKaWGywJQKaWU" +
    "UkoppZRSSqk3LgC1GTDAAAMMMMAAAwwwwAADDDDAAAMMMPCZmoEF4IFD0GbAAAMMMMAA" +
    "AwwwwAADDDDAAAMMMJAFIASCgAEGGGCAAQYYYIABBhhggAEGGGCAgX6cwRdDKuDi/tf/" +
    "lAAAAABJRU5ErkJggg==",
  "base64"
);

const PNG_160x120 = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAACXBIWXMAAAsTAAALEwEA" +
    "mpwYAAAJaElEQVR4nO1aZ3NV1xX1L4I0J5kk9mTS7LRx8iHBTvOkJ+PE42Q8ydiJxzPp" +
    "AdNtAwYThG1sTLcpVxUVUEUFISQhVAAhoV5Qryez9/O9nFf2E0iad7fuWWtmfdA5+922" +
    "1t3n7H31kLdxnQHxDLyQnsFDMB/M54X4DGBAGNCoMSAAZAIwIBAqYEAgVMCAQKiAAYFQ" +
    "AQMCa8uAaFWgV+gt4xnAgDCOCfMZwIAwoIEBYQJntzASsAdUII4LlAADKhDHBUqAARWI" +
    "4wIlwIAKxHGBEmBABeK4QAkwoAJxXKAEGFCBOC5QAgyoQBwXKAEGVCCOC5QAAyoQxwVK" +
    "gAEViOMCJcCACsRxgRJgQAXiuEAJMKACcVygBBhQgTguUAIMqEAcFygBBlQgjguUAAMq" +
    "EMcFSoABFYjjAiXAgArEcYESYEAF4rhACTCgAnFcoAQYUIE4LlACDKhAHBcoAQZUII4L" +
    "lAADKhDHBUqAARWI4wIlwIAKxHGBEmBABeK4QAkwoAJxXKAEGFCBOC5QAgyoQBwXKAEG" +
    "VCCOC5QAAyoQxwVKgAEViOMCJcCACsRxgRJgQAXiuEAJMKACcVygcd2ABa9+0Vw88D1T" +
    "/MY3TfYrn0gbm/3Kx03R7sdM4a6vmuxNH9Nz7Xu/ZbyN6+/jN+vN+de/bIr2PL7kvWaK" +
    "kTFgzpaHzdWcf5jxwQ4zOzVqWop3pI0vzXrSDHXWGGMWg3uYmx4zjbn/ShnfkP03Mz3e" +
    "H8ROjnab2pN/XLXrJ0PXnXrejN5p4OvvavggZVzh618xN6oOmpnxgbjnT9fWmPdv0YiX" +
    "jvzWTAzdDOJnJ4dNc8Gm0HVb8wbM2fxJc61wS5w5CK2le8TflL31AzM/O2kWFxdMT0u+" +
    "aSneadrL3zQDN8rNzepDSfH1Z//Kx5wa6zXXiraZ6xdeM7NTI/z76qPPrPge6Pj04tjo" +
    "uZabMrbu1POxF2DkNl8rXU9n3REzPzsVu++Lu5J+U/7OT8ziwpyZmxnn59J8frOZHO7k" +
    "+LBNuOYNWLjra3z+mYnBwBzpDEiZ5m5fC5un5sRzSfO5Wz8d//eWhznbLMzPmpK93w7G" +
    "K9/9GZ+HjLPS5ZiMMT8zYToqs8yVsy+lNWD52z82lz/8c9I5y976Id8TGS1/56NxcyPd" +
    "9XxM+2WhTOqbMn/HIzDgcsUr2Pmoacr7T2CcpoJNaQ3oG6f76un7On71sd9x/EBHadx4" +
    "R9XB4OUrO/hUMF51+JecpfJ3fCHltdIcxdjjLcXbA9NcOvKbtAb00nC0t4l/W3X4V8EY" +
    "7W05e9+9ExfbcO7l4PopA2cyaUQqAyZyKQO2le2NZYNjv7+v49HSTKBl3h8rzdpgFhfm" +
    "zfRYH8815W+8Z9ijz/C+srclP2E/tt70t5fwXLpleyUGHL5dy7+lJdcfqz/zIo/dvnIy" +
    "rnihLYR//Z2Xj8KAmTJg7/UCni898P3YZn5iiJeu8aEbvIQnLm09zTkcT5mL/qZ5KhTu" +
    "9jbz/omQuG/sqDzA47GiIDbmx7ZX7E97/cs14PnXvmQW5me4gMnZ/KlgvPXi7qS9IWX/" +
    "mclhU/fBn3hu8GYFDJgpAw51VvN8f/tF3v+QGJ31x4Mixs4URFp6eVl7/9ex4+f/lw1L" +
    "y66fXboSlnNqcQx31ZmFuWluk1DFTXtIylBLtT+Wa8C+1sKURcWN6nfisjTdBy+7p1/g" +
    "6yKM9jTCgJky4MidBp6nKrjkze/ELUtU5XJ2zHrSMuwlHqs49DT3/8i0lDlprvbkH3ju" +
    "TnN20nkKdz/GyxwVKdT+oLYHFUxLXf9yDNiY+8/gpUrM4Ldq3+c5aiNRQTUxfIvjaK5k" +
    "3xM8N9bfCgNmOgPeqj2cNOcvV9dLXg3GSCx/z0j7usmRLpO79TM851esXVdOpTxXzfFn" +
    "gz0yFTP3c/0PasCa489yRqYtQd72zyXN08vCe9iibaatbB+/eNSI9itnAr2Uq/X8H5TO" +
    "FSFkIgI1rRPnLp9+4aNN+bFgrKvhQx7zf0cN3cRz0Z4v1bmoqe0j1flWasCKQ0+b+blp" +
    "7unRHjBVDFXYhL62Ym670DUnnovmYMAMGbC94n9JBYLP+jN/iRmw7ogl4I7ARIl7Pdo7" +
    "8vJ27uWkY8X2fTPcg6OihfaDVD2vlgFLszbwlxuqZIve+IYYV3viueD6KdPZS7RfGFFL" +
    "CQbMkAFjbZLkYiNmzv2x5apwazBW/vaPeIwyDfXx7sWvN1Oj3TxXtOfrccfJ2/55zkpk" +
    "EDIHfaulvSPtv1Itkw9qwJJ9T3D1TpXsBWsfm4rUZKYlOrFfSexvvxDbHqzC15zl0rkl" +
    "mFoU1JSlqtTul5FJqFAgsWIf9+8ZjfZXBFqi/fGrOX9P2aCm+J5reTxHbY7E5Z3aOisx" +
    "YNGex83U3R7+9EYNZ2p4J9JuwxC7m87xMakH6o9Vvvdzvlfa04b5jwmRMKBfPEhI7L3R" +
    "Po72Q8TBW1VcaNCnMAJ9yks8funBpz761rpoBm9WBv/EQIaNN2usTUO4XX8i6ThUrKRa" +
    "/v1+nIS+1qIglr7jLgV6Oezj02c3v+lM2wF6aeje6SWsfO8XoWoXCQNSJUj7NonULkky" +
    "VdYG09141owPtnMWoK8UtF+SznFh/3dNd+MZbliPD7Sxwfxq0mfuts9yU5roV8pJ8zXv" +
    "Js3T0pju+hstw1IfL10sseLQT5POTUUKVf5jA23cFqJMbLebYMCQHwS4DhkQJnDvRZCw" +
    "ppZgcN2afQYwoAIRXKYEOwYZUIFQXkQJAyoQwWVKsGOQARUI5UWUMKACEVymBDsGGVCB" +
    "UF5ECQMqEMFlSrBjkAEVCOVFlDCgAhFcpgQ7BhlQgVBeRAkDKhDBZUqwY5ABFQjlRZQw" +
    "oAIRXKYEOwYZUIFQXkQJAyoQwWVKsGOQARUI5UWUMKACEVymBDsGGVCBUF5ECQMqEMFl" +
    "SrBjkAEVCOVFlDCgAhFcpgQ7BhlQgVBeRAkDKhDBZUqwY5ABFQjlRZQwoAIRXKYEOwYZ" +
    "UIFQXkQJAyoQwWVKsGOQARUI5UWUMKACEVymBDsGGVCBUF5ECQMqEMFlSrBjkAEVCOVF" +
    "lDCgAhFcpgQ7BhlQgVBeRAkDKhDBZUqwY5ABFQjlRZQwoAIRXKYEOwYZUIFQXkQJAyoQ" +
    "wWVKsGOQARUI5UWUMKACEVymhAfOgACwmoABgVABAwKhAgYEQgUMCIQKGBDQaUAQz8DL" +
    "8DOAAWE6E+YzgAFhQBNms/r/iQWW79X6EncAAAAASUVORK5CYII=",
  "base64"
);

let pool: Pool;
let mediaRoot: string;

const AGENT = "agt_backfill";

beforeAll(async () => {
  pool = await setupTestDb();
  await runTestMigrations();
  mediaRoot = await mkdtemp(path.join(tmpdir(), "dispatch-backfill-"));
  await mkdir(path.join(mediaRoot, AGENT), { recursive: true });
  await pool.query(
    `INSERT INTO agents (id, name, cwd, status) VALUES ($1, 'Backfill', '/tmp', 'running')`,
    [AGENT]
  );
});

afterAll(async () => {
  await rm(mediaRoot, { recursive: true, force: true });
  await teardownTestDb();
});

beforeEach(async () => {
  await pool.query("DELETE FROM media");
});

/** A media row with no dimensions, plus the file it points at. */
async function seedRow(
  fileName: string,
  bytes: Buffer | null
): Promise<number> {
  if (bytes) {
    await writeFile(path.join(mediaRoot, AGENT, fileName), bytes);
  }
  const result = await pool.query<{ id: number }>(
    `INSERT INTO media (agent_id, file_name, source, size_bytes)
     VALUES ($1, $2, 'screenshot', $3) RETURNING id`,
    [AGENT, fileName, bytes?.length ?? 0]
  );
  return result.rows[0]!.id;
}

const dimensionsOf = async (id: number) =>
  (
    await pool.query<{ width: number | null; height: number | null }>(
      `SELECT width, height FROM media WHERE id = $1`,
      [id]
    )
  ).rows[0]!;

describe("backfillMediaDimensions", () => {
  it("measures rows that have no dimensions yet", async () => {
    const wide = await seedRow("wide.png", PNG_1280x720);
    const thumb = await seedRow("thumb.png", PNG_160x120);

    const result = await backfillMediaDimensions(pool, mediaRoot);

    expect(result).toEqual({ scanned: 2, measured: 2 });
    expect(await dimensionsOf(wide)).toEqual({ width: 1280, height: 720 });
    expect(await dimensionsOf(thumb)).toEqual({ width: 160, height: 120 });
  });

  it("leaves a row alone when its file cannot be read", async () => {
    const missing = await seedRow("gone.png", null);
    const corrupt = await seedRow("corrupt.png", Buffer.from("not a png"));

    const result = await backfillMediaDimensions(pool, mediaRoot);

    expect(result.measured).toBe(0);
    expect(await dimensionsOf(missing)).toEqual({ width: null, height: null });
    expect(await dimensionsOf(corrupt)).toEqual({ width: null, height: null });
  });

  it("skips rows that are not images without counting them", async () => {
    await seedRow("notes.md", Buffer.from("# hi"));
    await seedRow("clip.mp4", Buffer.alloc(16));

    expect(await backfillMediaDimensions(pool, mediaRoot)).toEqual({
      scanned: 0,
      measured: 0,
    });
  });

  it("does not clobber a row a live writer fills between probe and write", async () => {
    // The sweep is detached from boot, so dispatch_share_file can replace the
    // bytes and commit their dimensions in the window between the probe and
    // the write. The live writer has to win: the one-shot flag means nothing
    // comes back later to repair a row left disagreeing with its file.
    const id = await seedRow("replaced.png", PNG_1280x720);

    const result = await backfillMediaDimensions(pool, mediaRoot, {
      // Fires after this row's bytes have been read and before it is written.
      afterProbe: async (probed) => {
        if (probed !== id) return;
        await pool.query(
          `UPDATE media SET width = 90, height = 120 WHERE id = $1`,
          [id]
        );
      },
    });

    expect(result.scanned).toBe(1);
    expect(result.measured).toBe(0);
    expect(await dimensionsOf(id)).toEqual({ width: 90, height: 120 });
  });

  it("skips a row that already had dimensions before the sweep started", async () => {
    const id = await seedRow("already-known.png", PNG_1280x720);
    await pool.query(
      `UPDATE media SET width = 90, height = 120 WHERE id = $1`,
      [id]
    );

    const result = await backfillMediaDimensions(pool, mediaRoot);

    // Filtered out by the query, so it is not even counted as scanned.
    expect(result).toEqual({ scanned: 0, measured: 0 });
    expect(await dimensionsOf(id)).toEqual({ width: 90, height: 120 });
  });

  it("pages past the first batch and covers every row", async () => {
    // A batch size of two against seven rows forces four SELECTs. One
    // unreadable row keeps its nulls throughout, so the walk cannot rely on
    // the candidate set shrinking as it goes — an OFFSET-based one would
    // start skipping rows here.
    const ids: number[] = [];
    for (let i = 0; i < 6; i++) {
      ids.push(await seedRow(`page-${i}.png`, PNG_160x120));
    }
    const stuck = await seedRow("page-stuck.png", Buffer.from("nope"));

    const result = await backfillMediaDimensions(pool, mediaRoot, {
      batchSize: 2,
    });

    expect(result).toEqual({ scanned: 7, measured: 6 });
    for (const id of ids) {
      expect(await dimensionsOf(id)).toEqual({ width: 160, height: 120 });
    }
    expect(await dimensionsOf(stuck)).toEqual({ width: null, height: null });
  });
});
