export type Surface = "inline" | "ambient";

export type Tip = {
  id: string;
  title: string;
  body: string;
  docsSection?: string;
  since: string;
  surfaces: Surface[];
  desktopOnly?: boolean;
};

export const tips: Tip[] = [
  {
    id: "agent-orchestration",
    title: "Agent Orchestration",
    body: "Agents can now launch other agents using the dispatch_launch_agent tool. Delegate subtasks, run parallel workstreams, or hand off work — launched agents coordinate via messaging.",
    docsSection: "agents",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "quick-phrases",
    title: "Quick Phrases",
    body: "Inject saved phrases into your terminal session with one click. Create reusable snippets for common commands.",
    docsSection: "agents#quick-phrases",
    since: "0.23.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "personas",
    title: "Personas",
    body: "Launch specialized review agents with structured feedback. Define reusable roles for security, UX, or code review.",
    docsSection: "personas",
    since: "0.22.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "brain",
    title: "Brain",
    body: "Repo-scoped shared memory that persists across agent sessions. Store objects, lists, and event logs your agents can manage.",
    docsSection: "tools#brain",
    since: "0.20.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "automations",
    title: "Automations",
    body: "Schedule recurring jobs like PR triage, dependency checks, or custom workflows on a cron schedule.",
    docsSection: "automations",
    since: "0.18.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "media-sidebar",
    title: "Media Sidebar",
    body: "View agent pins, screenshots, and shared media in a collapsible sidebar. Pin it to keep it visible while you work.",
    docsSection: "media",
    since: "0.19.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "file-upload",
    title: "File Upload",
    body: "Drag and drop files onto the terminal to upload and inject them into the agent's prompt. You can also paste images from your clipboard.",
    docsSection: "media#uploading-files",
    since: "0.23.6",
    surfaces: ["ambient"],
  },
  {
    id: "changes-tab",
    title: "Changes Tab",
    body: "Switch to the Changes tab next to Terminal to browse an agent's diff. Use the gear icon to toggle split/unified view and hide whitespace changes.",
    docsSection: "agents",
    since: "0.23.9",
    surfaces: ["ambient"],
  },
  {
    id: "uncommitted-diff",
    title: "Filter Uncommitted Changes",
    body: "Choose whether Changes includes uncommitted work.",
    docsSection: "agents#split-tabs",
    since: "0.28.2",
    surfaces: ["inline"],
  },
  {
    id: "split-tabs",
    title: "Split Tabs",
    body: "Drag the Changes tab to the left or right side of the center pane to compare the diff beside the live terminal. Use the split handle to resize or unsplit.",
    docsSection: "agents#split-tabs",
    since: "0.27.4",
    surfaces: ["inline", "ambient"],
    desktopOnly: true,
  },
  {
    id: "session-rename",
    title: "Rename Sessions",
    body: "Expand an agent in the sidebar and click the edit button to open session settings and rename it directly.",
    docsSection: "agents",
    since: "0.23.13",
    surfaces: ["ambient"],
  },
  {
    id: "sidebar-reorder",
    title: "Reorder Agents",
    body: "Drag and drop agent cards to reorder them, or focus a card and press Alt+↑ / Alt+↓. The order persists across sessions.",
    docsSection: "agents",
    since: "0.24.3",
    surfaces: ["ambient"],
  },
  {
    id: "keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    body: "Press Mod+K to open the command palette. Navigate agents, toggle sidebars, and control the terminal without touching the mouse.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "terminal-focus-shortcut",
    title: "Terminal Focus Shortcut",
    body: "Press Mod+Shift+Space to jump back to the terminal input from anywhere in Dispatch.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "sidebar-shortcuts",
    title: "Sidebar Shortcuts",
    body: "Press Mod+Shift+< to toggle the agent sidebar, or Mod+Shift+> to toggle the media sidebar.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "agent-navigation-shortcuts",
    title: "Agent Navigation Shortcuts",
    body: "Press Mod+Shift+↑ or Mod+Shift+↓ to move between top-level agents without leaving the keyboard.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "command-palette-shortcut",
    title: "Command Palette Shortcut",
    body: "Press Mod+K to search commands, open settings pages, or launch palette-enabled templates.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "worktrees",
    title: "Worktrees",
    body: "Each agent gets its own git worktree by default — isolated branches, no conflicts. Run multiple agents in parallel on the same repo.",
    docsSection: "worktrees",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "personalities",
    title: "Personalities",
    body: "Customize how agents communicate. Add a personality to shape tone, preferences, or standing instructions across all new agents.",
    docsSection: "personalities",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "notifications",
    title: "Notifications",
    body: "Get notified when agents finish, need input, or get stuck. Set up Slack, browser, or sound alerts in Settings.",
    docsSection: "notifications",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "diff-review",
    title: "Diff Review",
    body: "Select lines in the Changes tab and submit review comments. Both you and the agent can reply, resolve, or reopen items in threaded conversations.",
    docsSection: "agents",
    since: "0.27.0",
    surfaces: ["ambient"],
  },
  {
    id: "agent-messages",
    title: "Agent Messages",
    body: "Open the Messages tab in the media sidebar to see all inter-agent messages grouped by conversation partner, with delivery status and timestamps.",
    docsSection: "media",
    since: "0.28.0",
    surfaces: ["ambient"],
  },
  {
    id: "split-pane",
    title: "Split Pane",
    body: "Drag the Terminal or Changes tab to the left or right drop zone to view them side by side. Click the split button on the divider to unsplit.",
    docsSection: "agents",
    since: "0.27.0",
    surfaces: ["ambient"],
  },
  {
    id: "review-row-open",
    title: "Open Submitted Reviews",
    body: "A review agent's row lights up once its review is submitted. Click the row to open the review and work through its feedback.",
    docsSection: "personas",
    since: "0.29.1",
    surfaces: ["inline"],
  },
  {
    id: "browser-feedback",
    title: "Browser Feedback",
    body: "Select an element on any web page, add a comment, and send it to a running agent. Pair the Chrome extension from Settings → Connections.",
    docsSection: "browser-feedback",
    since: "0.29.3",
    surfaces: ["ambient"],
  },
  {
    id: "service-resources",
    title: "Service Resources",
    body: "Wondering how Dispatch is holding up? Settings → Resources charts live CPU, memory, subsystem health, and workload for the server, agents, and host.",
    docsSection: "resources",
    since: "0.30.0",
    surfaces: ["ambient"],
  },
  {
    id: "whiteboard",
    title: "Whiteboard",
    body: "Agents and users share a live whiteboard. Draw diagrams, sketch ideas, or annotate what an agent has started.",
    docsSection: "agents#whiteboard",
    since: "0.30.1",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "job-webhook-trigger",
    title: "Job Webhook Triggers",
    body: "Fire a job from CI or any external system: enable Webhook trigger in the job's Configure tab to get a secret URL that starts a run on HTTP POST.",
    docsSection: "automations",
    since: "0.29.0",
    surfaces: ["ambient"],
  },
  {
    id: "self-improve",
    title: "Self-Improving Automations",
    body: "Jobs and templates can refine their own prompts: turn on 'Self improve after each run' and the agent conservatively updates the saved prompt when it finds a durable improvement.",
    docsSection: "automations",
    since: "0.33.0",
    surfaces: ["ambient"],
  },
  {
    id: "prompt-delivery-hold",
    title: "Hold Prompts While You Type",
    body: "Tired of review feedback and agent messages landing mid-sentence? Settings → Agents can hold automated prompts until you pause typing — a badge over the terminal lets you send them early.",
    docsSection: "agents#prompt-delivery",
    since: "0.33.4",
    surfaces: ["ambient"],
  },
  {
    id: "built-in-reviewer",
    title: "Review With No Setup",
    body: "Every repo now has a built-in General Code Review persona, so you can launch a reviewer before writing a single persona file. Add .dispatch/personas/code-review.md to specialize it.",
    docsSection: "personas#built-in-reviewer",
    since: "0.33.6",
    surfaces: ["ambient"],
  },
  {
    id: "repo-tools",
    title: "Give Agents Your Repo's Commands",
    body: "Add a .dispatch/tools.json to a repo and every entry becomes a real tool in each agent's tool list — so nobody has to paste the same build, reset, or dev-stack command into a prompt again.",
    docsSection: "tools",
    since: "0.11.12",
    surfaces: ["ambient"],
  },
  {
    id: "shortcut-pins",
    title: "One-Click Agent Shortcuts",
    body: "Agents can pin a button to the Pins tab that sends a prompt back to them when you click it — approve a plan, kick off the next step, re-run a check without typing it out.",
    docsSection: "media#media-sidebar",
    since: "0.33.7",
    surfaces: ["ambient"],
  },
];

export function getTipById(id: string): Tip | undefined {
  return tips.find((t) => t.id === id);
}
