export type Surface = "inline" | "ambient";

export type Tip = {
  id: string;
  title: string;
  body: string;
  docsSection?: string;
  since: string;
  surfaces: Surface[];
  desktopOnly?: boolean;
};

export const tips: Tip[] = [
  {
    id: "agent-orchestration",
    title: "Agent Orchestration",
    body: "Agents can launch other agents with the launch_agent tool. Delegate subtasks, run parallel workstreams, or hand off work — children post into their parent's stream, so it all reads in one place.",
    docsSection: "agents",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "quick-phrases",
    title: "Quick Phrases",
    body: "Inject saved phrases into your terminal session with one click. Create reusable snippets for common commands.",
    docsSection: "agents#quick-phrases",
    since: "0.23.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "personas",
    title: "Personas",
    body: "Launch specialized reviewers as children of an agent. Each posts a review block with findings you and the agent resolve in threads. Define reusable roles for security, UX, or code review.",
    docsSection: "personas",
    since: "0.22.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "brain",
    title: "Brain",
    body: "Repo-scoped shared memory that persists across agent sessions. Store objects, lists, and event logs your agents can manage.",
    docsSection: "tools#brain",
    since: "0.20.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "automations",
    title: "Automations",
    body: "Schedule recurring jobs like PR triage, dependency checks, or custom workflows on a cron schedule.",
    docsSection: "automations",
    since: "0.18.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "media-sidebar",
    title: "Media Sidebar",
    body: "The sidebar's Rail shows what an agent is waiting on you for and the links it posted; Media holds its screenshots and files. Pin it to keep it visible while you work.",
    docsSection: "media",
    since: "0.19.0",
    surfaces: ["inline", "ambient"],
  },
  {
    id: "file-upload",
    title: "File Upload",
    body: "Drag and drop files onto the terminal to upload and inject them into the agent's prompt. You can also paste images from your clipboard.",
    docsSection: "media#uploading-files",
    since: "0.23.6",
    surfaces: ["ambient"],
  },
  {
    id: "changes-tab",
    title: "Changes Tab",
    body: "Switch to the Changes tab next to Terminal to browse an agent's diff. Use the gear icon to toggle split/unified view and hide whitespace changes.",
    docsSection: "agents",
    since: "0.23.9",
    surfaces: ["ambient"],
  },
  {
    id: "uncommitted-diff",
    title: "Filter Uncommitted Changes",
    body: "Choose whether Changes includes uncommitted work.",
    docsSection: "agents#split-tabs",
    since: "0.28.2",
    surfaces: ["inline"],
  },
  {
    id: "split-tabs",
    title: "Split Tabs",
    body: "Drag the Changes tab to the left or right side of the center pane to compare the diff beside the live terminal. Use the split handle to resize or unsplit.",
    docsSection: "agents#split-tabs",
    since: "0.27.4",
    surfaces: ["inline", "ambient"],
    desktopOnly: true,
  },
  {
    id: "session-rename",
    title: "Rename Sessions",
    body: "Expand an agent in the sidebar and click the edit button to open session settings and rename it directly.",
    docsSection: "agents",
    since: "0.23.13",
    surfaces: ["ambient"],
  },
  {
    id: "sidebar-reorder",
    title: "Reorder Agents",
    body: "Drag and drop agent cards to reorder them, or focus a card and press Alt+↑ / Alt+↓. The order persists across sessions.",
    docsSection: "agents",
    since: "0.24.3",
    surfaces: ["ambient"],
  },
  {
    id: "keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    body: "Press Mod+K to open the command palette. Navigate agents and toggle sidebars without touching the mouse.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "sidebar-shortcuts",
    title: "Sidebar Shortcuts",
    body: "Press Mod+Shift+< to toggle the agent sidebar, or Mod+Shift+> to toggle the media sidebar.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "agent-navigation-shortcuts",
    title: "Agent Navigation Shortcuts",
    body: "Press Mod+Shift+↑ or Mod+Shift+↓ to move between top-level agents without leaving the keyboard.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "command-palette-shortcut",
    title: "Command Palette Shortcut",
    body: "Press Mod+K to search commands, open settings pages, or launch palette-enabled templates.",
    docsSection: "shortcuts",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "worktrees",
    title: "Worktrees",
    body: "Each agent gets its own git worktree by default — isolated branches, no conflicts. Run multiple agents in parallel on the same repo.",
    docsSection: "worktrees",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "personalities",
    title: "Personalities",
    body: "Customize how agents communicate. Add a personality to shape tone, preferences, or standing instructions across all new agents.",
    docsSection: "personalities",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "notifications",
    title: "Notifications",
    body: "Get notified when agents finish, need input, or get stuck. Set up Slack, browser, or sound alerts in Settings.",
    docsSection: "notifications",
    since: "0.24.0",
    surfaces: ["ambient"],
  },
  {
    id: "split-pane",
    title: "Split Pane",
    body: "Drag the Terminal or Changes tab to the left or right drop zone to view them side by side. Click the split button on the divider to unsplit.",
    docsSection: "agents",
    since: "0.27.0",
    surfaces: ["ambient"],
  },
  {
    id: "browser-feedback",
    title: "Browser Feedback",
    body: "Select an element on any web page, add a comment, and send it to a running agent. Pair the Chrome extension from Settings → Connections.",
    docsSection: "browser-feedback",
    since: "0.29.3",
    surfaces: ["ambient"],
  },
  {
    id: "service-resources",
    title: "Service Resources",
    body: "Wondering how Dispatch is holding up? Settings → Resources charts live CPU, memory, subsystem health, and workload for the server, agents, and host.",
    docsSection: "resources",
    since: "0.30.0",
    surfaces: ["ambient"],
  },
  {
    id: "job-webhook-trigger",
    title: "Job Webhook Triggers",
    body: "Fire a job from CI or any external system: enable Webhook trigger in the job's Configure tab to get a secret URL that starts a run on HTTP POST.",
    docsSection: "automations",
    since: "0.29.0",
    surfaces: ["ambient"],
  },
  {
    id: "self-improve",
    title: "Self-Improving Automations",
    body: "Jobs and templates can refine their own prompts: turn on 'Self improve after each run' and the agent conservatively updates the saved prompt when it finds a durable improvement.",
    docsSection: "automations",
    since: "0.33.0",
    surfaces: ["ambient"],
  },
  {
    id: "built-in-reviewer",
    title: "Review With No Setup",
    body: "Every repo has a built-in code-review persona, so you can launch a reviewer from the Changes tab before writing a single persona file. Add .dispatch/personas/code-review.md to specialize it.",
    docsSection: "personas#built-in-reviewer",
    since: "0.33.6",
    surfaces: ["ambient"],
  },
  {
    id: "repo-tools",
    title: "Give Agents Your Repo's Commands",
    body: "Add a .dispatch/tools.json to a repo and every entry becomes a real tool in each agent's tool list — so nobody has to paste the same build, reset, or dev-stack command into a prompt again.",
    docsSection: "tools",
    since: "0.11.12",
    surfaces: ["ambient"],
  },
  {
    id: "job-webhooks",
    title: "Fire a Job From Anywhere",
    body: "A job's Configure tab has a Webhook trigger toggle: save it and you get a secret URL that starts a run on an HTTP POST — no auth header, so CI, a shortcut, or another machine can kick it off.",
    docsSection: "automations#on-demand-runs",
    since: "0.22.0",
    surfaces: ["ambient"],
  },
  {
    id: "dispatch-plugin",
    title: "Teach Your CLI About Dispatch",
    body: "Install the Dispatch plugin in Claude Code or Codex and agents pick up skills for the Brain, subagents, repo tools, personas and the stream — so they use them without being told.",
    docsSection: "plugin#plugin-install",
    since: "0.34.1",
    surfaces: ["ambient"],
  },
  {
    id: "launch-guidance-trim",
    title: "Shorter Startup Rules",
    body: "Running the Dispatch plugin? Settings → Agents → Launch guidance lets new Claude Code and Codex agents skip the rules the plugin's skills already cover, leaving more room for your prompt.",
    docsSection: "plugin#plugin-launch-guidance",
    since: "0.34.2",
    surfaces: ["ambient"],
  },
  {
    id: "sub-agents",
    title: "Sub Agents",
    body: "Agents launched by another agent now live in that agent's card — expand it to find the Sub Agents list, where each row has its own terminal, pause, settings, and archive actions.",
    docsSection: "agents#sub-agents",
    since: "0.35.0",
    surfaces: ["ambient"],
  },
  {
    id: "focus-suppression",
    title: "Quiet While You Watch",
    body: "Dispatch skips browser and Slack notifications for the agent you currently have selected in a visible, focused tab. Switch away, hide the tab, or blur the window and alerts for it resume right away.",
    docsSection: "notifications#focus-suppression",
    since: "0.11.12",
    surfaces: ["ambient"],
  },
  {
    id: "review-blocks",
    title: "Reviews Live in the Stream",
    body: "A reviewer posts one review block: verdict, summary and findings. Open a finding to discuss it in its thread, and resolve, dispute or reopen it right on the block.",
    docsSection: "personas",
    since: "0.38.0",
    surfaces: ["ambient"],
  },
  {
    id: "stream-rail",
    title: "The Rail",
    body: "The sidebar's Rail tab lists every question or form an agent is waiting on you for — answer it there without scrolling the chat — plus the links it has posted.",
    docsSection: "media#media-sidebar",
    since: "0.38.0",
    surfaces: ["ambient"],
  },
  {
    id: "create-with-context",
    title: "Start an Agent With Context",
    body: "The create dialog's second button, Create with context, opens a step for startup instructions, attached files, and links — so the session begins with what it needs instead of you pasting it into the terminal afterwards.",
    docsSection: "agents",
    since: "0.18.1",
    surfaces: ["ambient"],
  },
];

export function getTipById(id: string): Tip | undefined {
  return tips.find((t) => t.id === id);
}
