/**
 * Contracts both the API server and the web client have to agree on.
 *
 * Anything here is imported by `apps/server` and `apps/web` alike, so it must
 * stay dependency-free and runtime-free: no `node:` imports, no browser APIs.
 * Almost all of it is types; a value exported here lands in the browser bundle
 * and in the compiled server binary at once, so keep those to plain constants
 * that both sides genuinely have to agree on.
 */
export { AGENT_TYPES, CLI_AGENT_TYPES } from "./agent-types.js";
export type { AgentType, CliAgentType } from "./agent-types.js";
export type {
  AgentActivity,
  AgentGitContext,
  AgentRecord,
  AgentRole,
  AgentStatus,
  ArchivePhase,
  SetupPhase,
  StreamedAgentRecord,
  WorktreeCleanupMode,
} from "./agent-record.js";
export {
  CHAT_ATTACHMENTS_MAX,
  CHAT_GALLERY_MAX_TILES,
  CHAT_MESSAGE_MAX_CHARS,
  CHAT_QUESTION_OPTIONS_MAX,
  CHAT_REACTIONS_MAX,
  fileMedia,
  layoutAttachments,
} from "./chat-types.js";
export type {
  ChatAnswer,
  ChatAnswerRequest,
  ChatAnswerResponse,
  ChatAttachment,
  ChatAttachmentGroup,
  ChatFileAttachment,
  FileMedia,
  ChatAuthorKind,
  ChatChangedEvent,
  ChatEntryEvent,
  ChatReadEvent,
  ChatFeedEntry,
  ChatFeedResponse,
  ChatFileEntry,
  ChatMessage,
  ChatMessageEntry,
  ChatMessageKind,
  ChatMessageOrigin,
  ChatQuestion,
  ChatQuestionOption,
  ChatTurnEntry,
  ChatTurnPlanEntry,
  ChatTurnPrompt,
  ChatTurnQuestionRef,
  ChatTurnStep,
  ChatTurnStepStatus,
  RuntimeChangedEvent,
  ChatReaction,
  ChatReactionRequest,
  ChatReactionResponse,
  ChatSendRequest,
  ChatSendResponse,
  ChatUnreadSummary,
  ChatUserAttachmentInput,
} from "./chat-types.js";
export {
  BLOCK_ATTACHMENTS_MAX,
  BLOCK_CANCEL_REASON_MAX_CHARS,
  BLOCK_FORM_FIELDS_MAX,
  BLOCK_KINDS,
  BLOCK_OPTION_LABEL_MAX_CHARS,
  BLOCK_OPTIONS_MAX,
  BLOCK_REACTIONS_MAX,
  BLOCK_REVIEW_FINDINGS_MAX,
  BLOCK_TASKS_MAX,
  BLOCK_TEXT_MAX_CHARS,
  reviewFindings,
  reviewStatus,
} from "./block-types.js";
export type {
  Block,
  AgentTurnResponse,
  BlockActor,
  BlockAuthor,
  BlockAuthorKind,
  BlockDelivery,
  BlockDeliveryState,
  BlockFindingData,
  BlockLaunchState,
  BlockReviewInput,
  BlockShows,
  BlockStartup,
  BlockStartupStep,
  BlockBody,
  BlockCancellation,
  BlockFindingPatch,
  BlockFindingResolution,
  BlockFindingState,
  BlockFindingStatus,
  BlockFormData,
  BlockFormField,
  BlockFormFieldType,
  BlockFormState,
  BlockKind,
  BlockLinkData,
  BlockOption,
  BlockOrigin,
  BlockQuestionData,
  BlockQuestionState,
  BlockReaction,
  BlockReviewData,
  BlockReviewSeverity,
  BlockReviewState,
  BlockReviewStatus,
  BlockTaskStatus,
  BlockTasksData,
  BlockTextData,
  BlockTasksState,
  StreamAnswerRequest,
  StreamAnswerResponse,
  StreamBlockEntry,
  StreamChangedEvent,
  StreamEntry,
  StreamEntryEvent,
  StreamFeedResponse,
  StreamPostRequest,
  StreamPostResponse,
  StreamReactionRequest,
  StreamReactionResponse,
  StreamReadEvent,
  StreamStateRequest,
  StreamSubmitRequest,
  StreamThreadReadResponse,
  StreamThreadResponse,
} from "./block-types.js";
export { DIFF_IMAGE_MAX_BYTES } from "./diff-types.js";
export type {
  DiffFile,
  DiffFileStatus,
  DiffImageInfo,
  DiffResponse,
  DiffStats,
  DiffTotals,
  FileDiffResponse,
} from "./diff-types.js";
export type { SharedUiEvent } from "./ui-event-types.js";
